/* Generated from the client TPMS database export (2026-08-27).
   People are stand-ins; business records are the client's own.
   Regenerate with tools/ (see tools/README.md) — do not hand-edit. */
import type {
  AccessPermission, AccessRole, AccessRule, AccessUser,
} from '@/types/access'

export const ACCESS_RULES: AccessRule[] = []

export const ACCESS_PERMISSIONS: AccessPermission[] = [
  { id: "Admin - RBAC", description: "Admin RBAC", routes: ["/admin/*"] },
  { id: "activity-assign", description: "Activity Assign", routes: ["/activities/assign"] },
  { id: "activity-create", description: "Activity Create", routes: ["/activities/create"] },
  { id: "activity-delete", description: "Activity Delete", routes: ["/activities/delete"] },
  { id: "activity-index", description: "Activity Index", routes: ["/activities/index"] },
  { id: "activity-task-create", description: "Activity Task Create", routes: ["/activity-tasks/create"] },
  { id: "activity-task-delete", description: "Activity Task Delete", routes: ["/activity-tasks/delete"] },
  { id: "activity-task-index", description: "Activity Task Index", routes: ["/activity-tasks/index"] },
  { id: "activity-task-update", description: "Activity Task Update", routes: ["/activity-tasks/update"] },
  { id: "activity-task-view", description: "Activity Task View", routes: ["/activity-tasks/view"] },
  { id: "activity-update", description: "Activity Update", routes: ["/activities/update"] },
  { id: "activity-view", description: "Activity View", routes: ["/activities/view"] },
  { id: "admin-user-change-password", description: "Admin User Change Password", routes: [] },
  { id: "admin-user-login", description: "Admin User Login", routes: ["/admin/user/login"] },
  { id: "admin-user-logout", description: "Admin User Logout", routes: ["/admin/user/logout"] },
  { id: "admin-user-request-password-reset", description: "Admin User Request Password Reset", routes: ["/admin/user/request-password-reset"] },
  { id: "admin-user-reset-password", description: "Admin User Reset Password", routes: ["/admin/user/reset-password"] },
  { id: "admin-user-update", description: "Admin User Update", routes: ["/admin/user/update"] },
  { id: "aircraft-create", description: "Aircraft Create", routes: ["/aircraft/create"] },
  { id: "aircraft-delete", description: "Aircraft Delete", routes: ["/aircraft/delete"] },
  { id: "aircraft-index", description: "Aircraft Index", routes: ["/aircraft/index"] },
  { id: "aircraft-update", description: "Aircraft Update", routes: ["/aircraft/update"] },
  { id: "aircraft-view", description: "Aircraft View", routes: ["/aircraft/view"] },
  { id: "approval-aircraft-create", description: "Approval Aircraft Create", routes: ["/approval-aircraft/create"] },
  { id: "approval-aircraft-delete", description: "Approval Aircraft Delete", routes: ["/approval-aircraft/delete"] },
  { id: "approval-aircraft-index", description: "Approval Aircraft Index", routes: ["/approval-aircraft/index"] },
  { id: "approval-aircraft-update", description: "Approval Aircraft Update", routes: ["/approval-aircraft/update"] },
  { id: "approval-aircraft-view", description: "Approval Aircraft View", routes: ["/approval-aircraft/view"] },
  { id: "approval-create", description: "Approval Create", routes: ["/approval/create"] },
  { id: "approval-create-modal", description: "Approval Create Modal", routes: ["/approval/create_modal"] },
  { id: "approval-dashboard", description: "Approval Dashboard", routes: ["/approval/dashboard"] },
  { id: "approval-dashboard-tab-update", description: "Approval Dashboard Tab Update", routes: [] },
  { id: "approval-dashboard-update", description: "Approval Dashboard Update", routes: ["/approval/dashboard"] },
  { id: "approval-delete", description: "Approval Delete", routes: ["/approval/delete"] },
  { id: "approval-index", description: "Approval Index", routes: ["/approval/index"] },
  { id: "approval-serialnumber-create", description: "Approval Serial Number Create", routes: ["/approval-serialnumber/create"] },
  { id: "approval-serialnumber-delete", description: "Approval Serial Number Delete", routes: ["/approval-serialnumber/delete"] },
  { id: "approval-serialnumber-index", description: "Approval Serial Number Index", routes: ["/approval-serialnumber/index"] },
  { id: "approval-serialnumber-update", description: "Approval Serial Number Update", routes: ["/approval-serialnumber/update"] },
  { id: "approval-serialnumber-view", description: "Approval Serial Number View", routes: ["/approval-serialnumber/view"] },
  { id: "approval-update", description: "Approval Update", routes: ["/approval/update"] },
  { id: "approval-update-modal", description: "Approval Update Modal", routes: ["/approval/update_modal"] },
  { id: "approval-view", description: "Approval View", routes: [] },
  { id: "approval-view-modal", description: "Approval View", routes: ["/approval/view"] },
  { id: "approvalissue-create", description: "Approval Issue Create", routes: [] },
  { id: "approvalissue-delete", description: "Approval Issue Delete", routes: [] },
  { id: "approvalissue-index", description: "Approval Issue Index", routes: [] },
  { id: "approvalissue-update", description: "Approval Issue Update", routes: [] },
  { id: "approvalissue-view", description: "Approval Issue View", routes: [] },
  { id: "atachapter-create", description: "Atachapter Create", routes: [] },
  { id: "atachapter-delete", description: "Atachapter Delete", routes: [] },
  { id: "atachapter-index", description: "Atachapter Index", routes: [] },
  { id: "atachapter-update", description: "Atachapter Update", routes: [] },
  { id: "atachapter-view", description: "Atachapter View", routes: [] },
  { id: "atasubchapter-create", description: "Atasubchapter Create", routes: [] },
  { id: "atasubchapter-delete", description: "Atasubchapter Delete", routes: [] },
  { id: "atasubchapter-index", description: "Atasubchapter Index", routes: [] },
  { id: "atasubchapter-update", description: "Atasubchapter Update", routes: [] },
  { id: "atasubchapter-view", description: "Atasubchapter View", routes: [] },
  { id: "audit", description: "Audit", routes: ["/audit/*"] },
  { id: "beta-performance", description: "Beta Performance Hub", routes: ["/beta/*"] },
  { id: "beta-project-performance", description: "Beta Project Performance", routes: [] },
  { id: "beta-team-performance", description: "Beta Team Performance", routes: [] },
  { id: "certbasis-copy", description: "Certbasis Copy", routes: [] },
  { id: "certbasis-create", description: "Certbasis Create", routes: [] },
  { id: "certbasis-delete", description: "Certbasis Delete", routes: [] },
  { id: "certbasis-edit", description: "Certbasis Edit", routes: [] },
  { id: "certbasis-import", description: "Certbasis Impor", routes: [] },
  { id: "certbasis-index", description: "Certbasis Index", routes: [] },
  { id: "certbasis-update", description: "Certbasis Update", routes: [] },
  { id: "certbasis-view", description: "Certbasis View", routes: [] },
  { id: "certplan-copy", description: "Certplan Copy", routes: [] },
  { id: "certplan-create", description: "Certplan Create", routes: [] },
  { id: "certplan-dashboard", description: "Certplan Dashboard", routes: [] },
  { id: "certplan-delete", description: "Certplan Delete", routes: [] },
  { id: "certplan-index", description: "Certplan Index", routes: [] },
  { id: "certplan-initialize", description: "Certplan Initialize", routes: [] },
  { id: "certplan-update", description: "Certplan Updat", routes: [] },
  { id: "certplan-view", description: "Certplan View", routes: [] },
  { id: "checklist-create", description: "Checklist Create", routes: ["/checklist/create"] },
  { id: "checklist-delete", description: "Checklist Delete", routes: ["/checklist/delete"] },
  { id: "checklist-index", description: "Checklist Index", routes: ["/checklist/index"] },
  { id: "checklist-update", description: "Checklist Update", routes: ["/checklist/update"] },
  { id: "checklist-view", description: "Checklist View", routes: ["/checklist/view"] },
  { id: "company-create", description: "Company Create", routes: ["/companys/create"] },
  { id: "company-delete", description: "Company Delete", routes: ["/companys/delete"] },
  { id: "company-index", description: "Company Index", routes: ["/companys/index"] },
  { id: "company-update", description: "Company Update", routes: ["/companys/update"] },
  { id: "company-view", description: "Company View", routes: ["/companys/view"] },
  { id: "contact-create", description: "Contact Create", routes: ["/contacts/create"] },
  { id: "contact-delete", description: "Contact Delete", routes: ["/contacts/delete"] },
  { id: "contact-index", description: "Contact Index", routes: ["/contacts/index"] },
  { id: "contact-update", description: "Contact Update", routes: ["/contacts/update"] },
  { id: "contact-view", description: "Contact View", routes: ["/contacts/view"] },
  { id: "database-backup", description: "Database Backup", routes: ["/backuprestore/*"] },
  { id: "dds-create", description: "DDS - Create", routes: [] },
  { id: "dds-delete", description: "DDS - Delete", routes: [] },
  { id: "dds-index", description: "DDS - Index", routes: [] },
  { id: "dds-update", description: "DDS - Update", routes: [] },
  { id: "dds-view", description: "DDS - View", routes: [] },
  { id: "delegation-create", description: "Delegation Create", routes: [] },
  { id: "delegation-delete", description: "Delegation Delete", routes: [] },
  { id: "delegation-index", description: "Delegation Index", routes: [] },
  { id: "delegation-update", description: "Delegation Update", routes: [] },
  { id: "delegation-view", description: "Delegation View", routes: [] },
  { id: "deliverable-create", description: "Deliverable Create", routes: [] },
  { id: "deliverable-delete", description: "Deliverable Delete", routes: [] },
  { id: "deliverable-index", description: "Deliverable index", routes: [] },
  { id: "deliverable-update", description: "Deliverable Update", routes: [] },
  { id: "deliverable-view", description: "Deliverable View", routes: [] },
  { id: "deliverablerev-create", description: "Deliverable Rev Create", routes: [] },
  { id: "deliverablerev-delete", description: "Deliverable Rev Delete", routes: [] },
  { id: "deliverablerev-index", description: "Deliverable Rev Index", routes: [] },
  { id: "deliverablerev-update", description: "Deliverable Rev Update", routes: [] },
  { id: "deliverablerev-view", description: "Deliverable Rev View", routes: [] },
  { id: "designdata-create", description: "Designdata Create", routes: [] },
  { id: "designdata-delete", description: "Designdata Delete", routes: [] },
  { id: "designdata-generate", description: "Designdata Generate", routes: [] },
  { id: "designdata-index", description: "Designdata Index", routes: [] },
  { id: "designdata-update", description: "Designdata Update", routes: [] },
  { id: "designdata-view", description: "Designdata View", routes: [] },
  { id: "designdatarev-create", description: "Designdatarev Create", routes: [] },
  { id: "designdatarev-delete", description: "Designdatarev Delete", routes: [] },
  { id: "designdatarev-index", description: "Designdatarev Index", routes: [] },
  { id: "designdatarev-update", description: "Designdatarev Update", routes: [] },
  { id: "designdatarev-view", description: "Designdatarev View", routes: [] },
  { id: "discipline-create", description: "Discipline Create", routes: [] },
  { id: "discipline-delete", description: "Discipline Delete", routes: [] },
  { id: "discipline-index", description: "Discipline Index", routes: [] },
  { id: "discipline-update", description: "Discipline Update", routes: [] },
  { id: "discipline-view", description: "Discipline View", routes: [] },
  { id: "foc-create", description: "Foc Create", routes: [] },
  { id: "foc-delete", description: "Foc Delete", routes: [] },
  { id: "foc-index", description: "Foc Index", routes: [] },
  { id: "foc-update", description: "Foc Update", routes: [] },
  { id: "foc-view", description: "Foc View", routes: [] },
  { id: "gcp-copy", description: "Gcp Copy", routes: [] },
  { id: "gcp-create", description: "Gcp Create", routes: [] },
  { id: "gcp-dashboard", description: "Gcp Dashboard", routes: [] },
  { id: "gcp-dashboard-tab-update", description: "Gcp Dashboard Tab Update", routes: [] },
  { id: "gcp-dashboard-update", description: "Gcp Dashboard Update", routes: [] },
  { id: "gcp-delete", description: "Gcp Delete", routes: [] },
  { id: "gcp-index", description: "Gcp Index", routes: [] },
  { id: "gcp-menu", description: "Gcp - Menu", routes: [] },
  { id: "gcp-modify", description: "GCP Modify", routes: [] },
  { id: "gcp-update", description: "Gcp Update", routes: [] },
  { id: "gcp-view", description: "Gcp View", routes: [] },
  { id: "hoursworked-create", description: "Hours Worked Create", routes: ["/hours-worked/create"] },
  { id: "hoursworked-delete", description: "Hours Worked Delete", routes: ["/hours-worked/delete"] },
  { id: "hoursworked-index", description: "Hours Worked Index", routes: ["/hours-worked/index"] },
  { id: "hoursworked-report", description: "Hours Worked Report", routes: ["/hours-worked/*"] },
  { id: "hoursworked-update", description: "Hours Worked Update", routes: ["/hours-worked/update"] },
  { id: "hoursworked-validate", description: "Hoursworked Validate", routes: [] },
  { id: "hoursworked-view", description: "Hours Worked View", routes: ["/hours-worked/view"] },
  { id: "maintenance-menu", description: "Maintenance Menu", routes: [] },
  { id: "mastercertbasis-create", description: "Mastercertbasis Create", routes: [] },
  { id: "mastercertbasis-delete", description: "Mastercertbasis Delete", routes: [] },
  { id: "mastercertbasis-index", description: "Mastercertbasis Index", routes: [] },
  { id: "mastercertbasis-update", description: "Mastercertbasis Update", routes: [] },
  { id: "mastercertbasis-view", description: "Mastercertbasis View", routes: [] },
  { id: "moc-create", description: "Moc Create", routes: [] },
  { id: "moc-delete", description: "Moc Delete", routes: [] },
  { id: "moc-index", description: "Moc Index", routes: [] },
  { id: "moc-update", description: "Moc Update", routes: [] },
  { id: "moc-view", description: "Moc View", routes: [] },
  { id: "myaccount-menu", description: "My Account Menu", routes: [] },
  { id: "project-activity-create", description: "Project Activity Create", routes: ["/project-activity/create"] },
  { id: "project-activity-delete", description: "Project Activity Delete", routes: ["/project-activity/delete"] },
  { id: "project-activity-index", description: "Project Activity Index", routes: ["/project-activity/index"] },
  { id: "project-activity-update", description: "Project Activity Update", routes: ["/project-activity/update"] },
  { id: "project-activity-view", description: "Project Activity Index", routes: ["/project-activity/view"] },
  { id: "project-aircraft-create", description: "Project Aircraft Create", routes: ["/project-aircraft/create"] },
  { id: "project-aircraft-delete", description: "Project Aircraft Delete", routes: ["/project-aircraft/delete"] },
  { id: "project-aircraft-index", description: "Project Aircraft Index", routes: ["/project-aircraft/index"] },
  { id: "project-aircraft-update", description: "Project Aircraft Update", routes: ["/project-aircraft/update"] },
  { id: "project-aircraft-view", description: "Project Aircraft View", routes: ["/project-aircraft/view"] },
  { id: "project-analysis", description: "Project Analysis", routes: [] },
  { id: "project-approval-create", description: "Project Approval Create", routes: ["/project-approval/create"] },
  { id: "project-approval-delete", description: "Project Approval Delete", routes: ["/project-approval/delete"] },
  { id: "project-approval-index", description: "Project Approval Index", routes: ["/project-approval/index"] },
  { id: "project-approval-update", description: "Project Approval Update", routes: ["/project-approval/update"] },
  { id: "project-approval-view", description: "Project Approval View", routes: ["/project-approval/view"] },
  { id: "project-assign", description: "Project Assign", routes: ["/projects/assign"] },
  { id: "project-contract-value-visible", description: "Project Contract Value Field - Visible", routes: [] },
  { id: "project-create", description: "Project Create", routes: ["/projects/create"] },
  { id: "project-currency-visible", description: "Project Currency Field - Visible", routes: [] },
  { id: "project-dashboard", description: "Project Dashboard", routes: ["/projects/dashboard"] },
  { id: "project-dashboard-tab-deliverablerev-update", description: "Project Dashboard Tab Deliverablerev - Update", routes: [] },
  { id: "project-dashboard-tab-designdatarev-update", description: "Project Dashboard Tab  Designdatarev Update", routes: [] },
  { id: "project-dashboard-tab-update", description: "Project Dashboard Tab Update", routes: [] },
  { id: "project-dashboard-update", description: "Project Dashboard Update", routes: ["/projects/dashboard"] },
  { id: "project-delete", description: "Project Delete", routes: ["/projects/delete"] },
  { id: "project-deliverablerev-create", description: "Project Deliverablerev Create", routes: ["/project-deliverablerev/create"] },
  { id: "project-deliverablerev-delete", description: "Project Deliverablerev Delete", routes: ["/project-deliverablerev/delete"] },
  { id: "project-deliverablerev-index", description: "Project Deliverablerev Index", routes: ["/project-deliverablerev/index"] },
  { id: "project-deliverablerev-update", description: "Project Deliverablerev Update", routes: ["/project-deliverablerev/update"] },
  { id: "project-deliverablerev-view", description: "Project Deliverablerev View", routes: ["/project-deliverablerev/view"] },
  { id: "project-designdatarev-create", description: "Project Designdatarev Create", routes: [] },
  { id: "project-designdatarev-delete", description: "Project Designdatarev Delete", routes: [] },
  { id: "project-designdatarev-index", description: "Project Designdatarev Index", routes: [] },
  { id: "project-designdatarev-update", description: "Project Designdatarev Update", routes: [] },
  { id: "project-designdatarev-view", description: "Project Designdatarev View", routes: [] },
  { id: "project-detail", description: "Project Detail", routes: [] },
  { id: "project-index", description: "Project Index", routes: ["/projects/index"] },
  { id: "project-management-menu", description: "Project Management Menu", routes: [] },
  { id: "project-report", description: "Project Report", routes: [] },
  { id: "project-review", description: "Project Review", routes: [] },
  { id: "project-review-client", description: "Project Review - Client", routes: [] },
  { id: "project-review-tab-1", description: "Project Review - Tab 1", routes: [] },
  { id: "project-review-tab-2", description: "Project Review - Tab 2", routes: [] },
  { id: "project-review-tab-3", description: "Project Review - Tab 3", routes: [] },
  { id: "project-review-tab-3-hours", description: "Project Review Tab 3 - hours", routes: [] },
  { id: "project-review-tab-4", description: "Project Review - Tab 4", routes: [] },
  { id: "project-review-tab-5", description: "Project Review - Tab 5", routes: [] },
  { id: "project-review-tab-6", description: "Project Review - Tab 6", routes: [] },
  { id: "project-review-tab-7", description: "Project Review - Tab 7", routes: [] },
  { id: "project-review-tab-8", description: "Project Review - Tab 8", routes: [] },
  { id: "project-update", description: "Project Update", routes: ["/projects/update"] },
  { id: "project-view", description: "Project View", routes: ["/projects/view"] },
  { id: "regulation-checklist", description: "Regulation Checklist", routes: [] },
  { id: "regulation-copy", description: "Regulation Copy", routes: [] },
  { id: "regulation-create", description: "Regulation Create", routes: [] },
  { id: "regulation-delete", description: "Regulation Delete", routes: [] },
  { id: "regulation-index", description: "Regulation Index", routes: [] },
  { id: "regulation-selectchecklist", description: "Regulation Select Checklist", routes: [] },
  { id: "regulation-update", description: "Regulation Update", routes: [] },
  { id: "regulation-view", description: "Regulation View", routes: [] },
  { id: "regulationgroup-create", description: "Regulation Group Create", routes: [] },
  { id: "regulationgroup-delete", description: "Regulation Group Delete", routes: [] },
  { id: "regulationgroup-index", description: "Regulation Group Index", routes: [] },
  { id: "regulationgroup-update", description: "Regulation Group Update", routes: [] },
  { id: "regulationgroup-view", description: "Regulation Group View", routes: [] },
  { id: "regulationgroupsection-create", description: "Regulation Group Section Create", routes: [] },
  { id: "regulationgroupsection-delete", description: "Regulation Group Section Delete", routes: [] },
  { id: "regulationgroupsection-edit", description: "Regulation Group Section Edit", routes: [] },
  { id: "regulationgroupsection-index", description: "Regulation Group Section Index", routes: [] },
  { id: "regulationgroupsection-update", description: "Regulation Group Section Update", routes: [] },
  { id: "regulationgroupsection-view", description: "Regulation Group Section View", routes: [] },
  { id: "report-create", description: "Report Create", routes: ["/report/create"] },
  { id: "report-delete", description: "Report Delete", routes: ["/report/delete"] },
  { id: "report-generator", description: "Report Generator", routes: [] },
  { id: "report-index", description: "Report Index", routes: ["/report/index"] },
  { id: "report-list-gcp", description: "Report List - Gcp", routes: [] },
  { id: "report-list-pm", description: "Report List - Project Management", routes: ["/report/list_pm"] },
  { id: "report-list-tt", description: "Report List - Time Tracking", routes: ["/report/list_tt"] },
  { id: "report-update", description: "Report Update", routes: ["/report/update"] },
  { id: "report-view", description: "Report View", routes: ["/report/view"] },
  { id: "serialnumber-create", description: "Serial Number Create", routes: ["/serialnumber/create"] },
  { id: "serialnumber-delete", description: "Serial Number Delete", routes: ["/serialnumber/delete"] },
  { id: "serialnumber-index", description: "Serial Number Index", routes: ["/serialnumber/index"] },
  { id: "serialnumber-update", description: "Serial Number Update", routes: ["/serialnumber/update"] },
  { id: "serialnumber-view", description: "Serial Number View", routes: ["/serialnumber/view"] },
  { id: "setting", description: "Setting", routes: ["/settings/*"] },
  { id: "show-field", description: "Show Field", routes: [] },
  { id: "show-hidden-field", description: "Show Hidden Field", routes: [] },
  { id: "subpart-create", description: "Subpart Create", routes: [] },
  { id: "subpart-delete", description: "Subpart Delete", routes: [] },
  { id: "subpart-index", description: "Subpart Index", routes: [] },
  { id: "subpart-update", description: "Subpart Update", routes: [] },
  { id: "subpart-view", description: "Subpart View", routes: [] },
  { id: "subsection-create", description: "Subsection Create", routes: [] },
  { id: "subsection-delete", description: "Subsection Delete", routes: [] },
  { id: "subsection-index", description: "Subsection Index", routes: [] },
  { id: "subsection-update", description: "Subsection Update", routes: [] },
  { id: "subsection-view", description: "Subsection View", routes: [] },
  { id: "task-create", description: "Task Create", routes: ["/tasks/create"] },
  { id: "task-delete", description: "Task Delete", routes: ["/tasks/delete"] },
  { id: "task-group-create", description: "Task Group create", routes: [] },
  { id: "task-group-delete", description: "Task Group delete", routes: [] },
  { id: "task-group-index", description: "Task Group Index", routes: [] },
  { id: "task-group-update", description: "Task Group update", routes: [] },
  { id: "task-group-view", description: "Task Group view", routes: [] },
  { id: "task-index", description: "Task Index", routes: ["/tasks/index"] },
  { id: "task-update", description: "Task Update", routes: ["/tasks/update"] },
  { id: "task-view", description: "Task View", routes: ["/tasks/view"] },
  { id: "tccadocstatus-create", description: "Tcca Docstatus Create", routes: ["/tccadocstatus/create"] },
  { id: "tccadocstatus-delete", description: "Tcca Docstatus Delete", routes: ["/tccadocstatus/delete"] },
  { id: "tccadocstatus-index", description: "Tcca Docstatus Index", routes: ["/tccadocstatus/index"] },
  { id: "tccadocstatus-update", description: "Tcca Docstatus Update", routes: ["/tccadocstatus/update"] },
  { id: "tccadocstatus-view", description: "Tcca Docstatus View", routes: ["/tccadocstatus/view"] },
  { id: "tccaproject-associate", description: "Tccaproject  Associate", routes: [] },
  { id: "tccaproject-create", description: "TCCA Project Create", routes: [] },
  { id: "tccaproject-dashboard", description: "TCCA Project Dashboard", routes: [] },
  { id: "tccaproject-dashboard-tab-update", description: "Tccaproject Dashboard Tab Update", routes: [] },
  { id: "tccaproject-dashboard-update", description: "Tccaproject Dashboard Update", routes: ["/tccaproject/dashboard"] },
  { id: "tccaproject-delete", description: "TCCA Project Delete", routes: [] },
  { id: "tccaproject-deliverablerev-create", description: "Tcca Project Deliverable Rev Create", routes: [] },
  { id: "tccaproject-deliverablerev-delete", description: "Tcca Project Deliverable Rev Delete", routes: [] },
  { id: "tccaproject-deliverablerev-index", description: "Tcca Project Deliverable Rev Index", routes: [] },
  { id: "tccaproject-deliverablerev-update", description: "Tcca Project Deliverable Rev Update", routes: [] },
  { id: "tccaproject-deliverablerev-view", description: "Tcca Project Deliverable Rev View", routes: [] },
  { id: "tccaproject-index", description: "TCCA Project Index", routes: [] },
  { id: "tccaproject-project-create", description: "Tcca Project Project Create", routes: [] },
  { id: "tccaproject-project-delete", description: "Tcca Project Project Delete", routes: [] },
  { id: "tccaproject-project-index", description: "Tcca Project Project Index", routes: [] },
  { id: "tccaproject-project-update", description: "Tcca Project Project Update", routes: [] },
  { id: "tccaproject-project-view", description: "Tcca Project Project View", routes: [] },
  { id: "tccaproject-update", description: "TCCA Project Update", routes: [] },
  { id: "tccaproject-view", description: "TCCA Project View", routes: [] },
  { id: "time-tracking-menu", description: "Time Tracking Menu", routes: [] },
  { id: "timesheet-copy", description: "Timesheet Copy", routes: [] },
  { id: "timesheet-create", description: "Timesheet Create", routes: ["/timesheet/create"] },
  { id: "timesheet-delete", description: "Timesheet Delete", routes: ["/timesheet/delete"] },
  { id: "timesheet-index", description: "Timesheet Index", routes: ["/timesheet/index"] },
  { id: "timesheet-update", description: "Timesheet Update", routes: ["/timesheet/update"] },
  { id: "timesheet-view", description: "Timesheet View", routes: ["/timesheet/view"] },
  { id: "user-Index", description: "User Index", routes: ["/user/index"] },
  { id: "user-access-control", description: "User Access Control", routes: ["/user/*"] },
  { id: "user-create", description: "User Create", routes: ["/user/create"] },
  { id: "user-delete", description: "User Delete", routes: ["/user/delete"] },
  { id: "user-maintenance", description: "User Maintenance", routes: [] },
  { id: "user-update", description: "User Update", routes: ["/user/update"] },
  { id: "user-view", description: "User View", routes: ["/user/view"] },
  { id: "userdashboard-detail", description: "User Dashboard Detail", routes: [] },
  { id: "userdashboard-update", description: "User Dashboard Update", routes: [] },
  { id: "userdashboard-view", description: "User Dashboard View", routes: [] },
  { id: "usergroup-create", description: "User Group Create", routes: ["/user-groups/create"] },
  { id: "usergroup-delete", description: "User Group Delete", routes: ["/user-groups/delete"] },
  { id: "usergroup-index", description: "User Groups Index", routes: ["/user-groups/index"] },
  { id: "usergroup-update", description: "User Group Update", routes: ["/user-groups/update"] },
  { id: "usergroup-view", description: "User Group View", routes: ["/user-groups/view"] },
  { id: "userprofile-create", description: "User Profile Create", routes: ["/user-profile/create"] },
  { id: "userprofile-delete", description: "User Profile Delete", routes: ["/user-profile/delete"] },
  { id: "userprofile-index", description: "User Profile Index", routes: ["/user-profile/index"] },
  { id: "userprofile-update", description: "User Profile Update", routes: ["/user-profile/update"] },
  { id: "userprofile-view", description: "User Profile View", routes: ["/user-profile/view"] },
]

export const ROUTE_REGISTRY: string[] = ["/*", "/actions/*", "/actions/create", "/actions/delete", "/actions/index", "/actions/update", "/actions/view", "/activities/*", "/activities/assign", "/activities/create", "/activities/delete", "/activities/index", "/activities/list", "/activities/update", "/activities/view", "/activity-tasks/*", "/activity-tasks/create", "/activity-tasks/delete", "/activity-tasks/index", "/activity-tasks/update", "/activity-tasks/view", "/admin/*", "/admin/assignment/*", "/admin/assignment/assign", "/admin/assignment/index", "/admin/assignment/revoke", "/admin/assignment/view", "/admin/default/*", "/admin/default/index", "/admin/menu/*", "/admin/menu/create", "/admin/menu/delete", "/admin/menu/index", "/admin/menu/update", "/admin/menu/view", "/admin/permission/*", "/admin/permission/assign", "/admin/permission/create", "/admin/permission/delete", "/admin/permission/get-users", "/admin/permission/index", "/admin/permission/remove", "/admin/permission/update", "/admin/permission/view", "/admin/role/*", "/admin/role/assign", "/admin/role/create", "/admin/role/delete", "/admin/role/get-users", "/admin/role/index", "/admin/role/remove", "/admin/role/update", "/admin/role/view", "/admin/route/*", "/admin/route/assign", "/admin/route/create", "/admin/route/index", "/admin/route/refresh", "/admin/route/remove", "/admin/rule/*", "/admin/rule/create", "/admin/rule/delete", "/admin/rule/index", "/admin/rule/update", "/admin/rule/view", "/admin/user/*", "/admin/user/activate", "/admin/user/change-password", "/admin/user/delete", "/admin/user/index", "/admin/user/login", "/admin/user/logout", "/admin/user/request-password-reset", "/admin/user/reset-password", "/admin/user/signup", "/admin/user/update", "/admin/user/view", "/aircraft/*", "/aircraft/create", "/aircraft/delete", "/aircraft/index", "/aircraft/update", "/aircraft/view", "/approval-aircraft/*", "/approval-aircraft/create", "/approval-aircraft/delete", "/approval-aircraft/index", "/approval-aircraft/update", "/approval-aircraft/view", "/approval-serialnumber/*", "/approval-serialnumber/create", "/approval-serialnumber/delete", "/approval-serialnumber/index", "/approval-serialnumber/update", "/approval-serialnumber/view", "/approval/*", "/approval/create", "/approval/create_modal", "/approval/dashboard", "/approval/delete", "/approval/index", "/approval/update", "/approval/update_modal", "/approval/view", "/approval/view-modal", "/approval/view_modal", "/approvalissue/*", "/approvalissue/create", "/approvalissue/create_modal", "/approvalissue/delete", "/approvalissue/index", "/approvalissue/update", "/approvalissue/update_modal", "/approvalissue/view", "/approvalissue/view_modal", "/approvals/*", "/approvals/create", "/approvals/create_modal", "/approvals/delete", "/approvals/index", "/approvals/update", "/approvals/update_modal", "/approvals/view", "/approvals/view_modal", "/audit/*", "/audit/default/*", "/audit/default/index", "/audit/entry/*", "/audit/entry/db-explain", "/audit/entry/index", "/audit/entry/view", "/audit/error/*", "/audit/error/index", "/audit/error/view", "/audit/javascript/*", "/audit/javascript/index", "/audit/javascript/view", "/audit/js-log/*", "/audit/js-log/index", "/audit/mail/*", "/audit/mail/download", "/audit/mail/index", "/audit/mail/view", "/audit/mail/view-html", "/audit/trail/*", "/audit/trail/index", "/audit/trail/view", "/backuprestore/*", "/backuprestore/default/*", "/backuprestore/default/clean", "/backuprestore/default/create", "/backuprestore/default/delete", "/backuprestore/default/download", "/backuprestore/default/index", "/backuprestore/default/restore", "/backuprestore/default/syncdown", "/backuprestore/default/upload", "/beta/*", "/checklist/*", "/checklist/create", "/checklist/delete", "/checklist/index", "/checklist/update", "/checklist/view", "/companys/*", "/companys/create", "/companys/delete", "/companys/index", "/companys/report", "/companys/update", "/companys/view", "/contacts/*", "/contacts/create", "/contacts/delete", "/contacts/get-contacts", "/contacts/index", "/contacts/list", "/contacts/update", "/contacts/view", "/deliverable/*", "/deliverable/create", "/deliverable/delete", "/deliverable/index", "/deliverable/list", "/deliverable/update", "/deliverable/view", "/deliverablerev/*", "/deliverablerev/create", "/deliverablerev/create_modal", "/deliverablerev/delete", "/deliverablerev/index", "/deliverablerev/update", "/deliverablerev/update_modal", "/deliverablerev/view", "/deliverablerev/view_modal", "/hours-worked/*", "/hours-worked/create", "/hours-worked/delete", "/hours-worked/index", "/hours-worked/timesheet", "/hours-worked/update", "/hours-worked/view", "/project-activity/*", "/project-activity/create", "/project-activity/delete", "/project-activity/index", "/project-activity/update", "/project-activity/view", "/project-aircraft/*", "/project-aircraft/create", "/project-aircraft/delete", "/project-aircraft/index", "/project-aircraft/update", "/project-aircraft/view", "/project-approval/*", "/project-approval/create", "/project-approval/delete", "/project-approval/index", "/project-approval/update", "/project-approval/view", "/project-deliverablerev/*", "/project-deliverablerev/create", "/project-deliverablerev/delete", "/project-deliverablerev/index", "/project-deliverablerev/update", "/project-deliverablerev/view", "/project/review", "/projects-activities/*", "/projects-activities/assign", "/projects/*", "/projects/assign", "/projects/create", "/projects/dashboard", "/projects/delete", "/projects/get-project-description", "/projects/index", "/projects/update", "/projects/view", "/report/*", "/report/create", "/report/delete", "/report/index", "/report/list_pm", "/report/list_tt", "/report/update", "/report/view", "/serialnumber/create", "/serialnumber/delete", "/serialnumber/index", "/serialnumber/update", "/serialnumber/view", "/settings/*", "/site/*", "/site/about", "/site/captcha", "/site/contact", "/site/error", "/site/index", "/site/login", "/site/logout", "/task-groups/*", "/task-groups/create", "/task-groups/delete", "/task-groups/index", "/task-groups/update", "/task-groups/view", "/tasks/*", "/tasks/assign", "/tasks/create", "/tasks/delete", "/tasks/index", "/tasks/list", "/tasks/update", "/tasks/view", "/tccadocstatus/*", "/tccadocstatus/create", "/tccadocstatus/delete", "/tccadocstatus/index", "/tccadocstatus/update", "/tccadocstatus/view", "/tccaproject-deliverablerev/*", "/tccaproject-deliverablerev/create", "/tccaproject-deliverablerev/delete", "/tccaproject-deliverablerev/index", "/tccaproject-deliverablerev/view", "/tccaproject-project/*", "/tccaproject-project/create", "/tccaproject-project/delete", "/tccaproject-project/index", "/tccaproject-project/view", "/tccaproject/*", "/tccaproject/create", "/tccaproject/create_-modal", "/tccaproject/dashboard", "/tccaproject/delete", "/tccaproject/index", "/tccaproject/update", "/tccaproject/update_modal", "/tccaproject/view", "/tccaproject/view_modal", "/timesheet/*", "/timesheet/create", "/timesheet/delete", "/timesheet/index", "/timesheet/list", "/timesheet/timesheet", "/timesheet/update", "/timesheet/view", "/user-groups/*", "/user-groups/create", "/user-groups/delete", "/user-groups/index", "/user-groups/update", "/user-groups/view", "/user-profile/*", "/user-profile/create", "/user-profile/delete", "/user-profile/index", "/user-profile/update", "/user-profile/view", "/user/*", "/user/create", "/user/delete", "/user/index", "/user/update", "/user/view"]

const GRANTED = new Set(ACCESS_PERMISSIONS.flatMap((p) => p.routes))

/** Routes no permission covers — visible so a gap can't hide. */
export const UNASSIGNED_ROUTES = ROUTE_REGISTRY.filter((r) => !GRANTED.has(r))

export const ACCESS_ROLES: AccessRole[] = [
  { id: "Client - Employee", name: "Client - Employee", description: "Client - Employee", permissionIds: ["deliverablerev-update", "deliverablerev-view", "designdatarev-update", "designdatarev-view", "project-detail", "project-management-menu", "project-review", "project-review-client", "project-review-tab-3", "project-view", "userdashboard-detail", "userdashboard-update", "userdashboard-view"], childRoleIds: [] },
  { id: "Client - Manager", name: "Client - Manager", description: "Client - Manager", permissionIds: [], childRoleIds: ["Client - Employee"] },
  { id: "Elisen - Admin", name: "Elisen - Admin", description: "Elisen - Administrator", permissionIds: ["Admin - RBAC", "admin-user-update", "beta-performance", "database-backup", "hoursworked-report", "report-generator", "report-list-pm", "report-list-tt", "setting", "task-create", "task-delete", "task-index", "task-update", "task-view", "user-Index", "user-access-control", "user-create", "user-delete", "user-maintenance", "user-update", "user-view", "usergroup-create", "usergroup-delete", "usergroup-index", "usergroup-update", "usergroup-view", "userprofile-create", "userprofile-delete", "userprofile-index", "userprofile-update", "userprofile-view"], childRoleIds: ["Elisen - Manager"] },
  { id: "Elisen - Employee", name: "Elisen - Employee", description: "Elisen - Employee", permissionIds: ["admin-user-login", "admin-user-logout", "admin-user-request-password-reset", "admin-user-reset-password", "approval-dashboard", "approval-index", "approval-view", "atachapter-index", "atachapter-view", "atasubchapter-index", "atasubchapter-view", "deliverable-index", "deliverable-view", "deliverablerev-index", "deliverablerev-update", "deliverablerev-view", "designdatarev-update", "designdatarev-view", "myaccount-menu", "project-dashboard", "project-dashboard-tab-deliverablerev-update", "project-dashboard-tab-designdatarev-update", "project-detail", "project-index", "project-management-menu", "project-view", "report-list-pm", "show-field", "tccaproject-dashboard", "tccaproject-index", "tccaproject-view", "time-tracking-menu", "timesheet-copy", "timesheet-create", "timesheet-delete", "timesheet-index", "timesheet-update", "timesheet-view", "userdashboard-detail", "userdashboard-update", "userdashboard-view"], childRoleIds: [] },
  { id: "Elisen - Manager", name: "Elisen - Manager", description: "Elisen - Manager", permissionIds: ["activity-create", "activity-delete", "activity-index", "activity-task-create", "activity-task-delete", "activity-task-index", "activity-task-update", "activity-task-view", "activity-update", "activity-view", "aircraft-create", "aircraft-delete", "aircraft-index", "aircraft-update", "aircraft-view", "approval-aircraft-create", "approval-aircraft-delete", "approval-aircraft-index", "approval-aircraft-update", "approval-aircraft-view", "approval-create", "approval-create-modal", "approval-dashboard", "approval-dashboard-update", "approval-delete", "approval-index", "approval-serialnumber-create", "approval-serialnumber-delete", "approval-serialnumber-index", "approval-serialnumber-update", "approval-serialnumber-view", "approval-update", "approval-update-modal", "approval-view-modal", "approvalissue-create", "approvalissue-delete", "approvalissue-index", "approvalissue-update", "approvalissue-view", "atachapter-delete", "atasubchapter-delete", "beta-performance", "certbasis-create", "certbasis-delete", "certbasis-import", "certbasis-index", "certbasis-update", "certbasis-view", "certplan-create", "certplan-delete", "certplan-index", "certplan-initialize", "certplan-update", "certplan-view", "checklist-create", "checklist-delete", "checklist-index", "checklist-update", "checklist-view", "company-create", "company-delete", "company-index", "company-update", "company-view", "contact-create", "contact-delete", "contact-index", "contact-update", "contact-view", "delegation-create", "delegation-delete", "delegation-index", "delegation-update", "delegation-view", "deliverable-create", "deliverable-delete", "deliverable-index", "deliverable-update", "deliverable-view", "deliverablerev-create", "deliverablerev-delete", "deliverablerev-index", "deliverablerev-update", "deliverablerev-view", "designdata-create", "designdata-delete", "designdata-generate", "designdata-index", "designdata-update", "designdata-view", "designdatarev-create", "designdatarev-delete", "designdatarev-index", "designdatarev-update", "designdatarev-view", "discipline-create", "discipline-delete", "discipline-index", "discipline-update", "discipline-view", "foc-create", "foc-delete", "foc-index", "foc-update", "foc-view", "gcp-create", "gcp-dashboard", "gcp-dashboard-tab-update", "gcp-dashboard-update", "gcp-delete", "gcp-index", "gcp-update", "gcp-view", "hoursworked-create", "hoursworked-delete", "hoursworked-index", "hoursworked-update", "hoursworked-view", "maintenance-menu", "mastercertbasis-create", "mastercertbasis-delete", "mastercertbasis-index", "mastercertbasis-update", "mastercertbasis-view", "moc-create", "moc-delete", "moc-index", "moc-update", "moc-view", "project-activity-create", "project-activity-delete", "project-activity-index", "project-activity-update", "project-activity-view", "project-aircraft-create", "project-aircraft-delete", "project-aircraft-index", "project-aircraft-update", "project-aircraft-view", "project-analysis", "project-approval-create", "project-approval-delete", "project-approval-index", "project-approval-update", "project-approval-view", "project-contract-value-visible", "project-create", "project-currency-visible", "project-dashboard", "project-dashboard-tab-designdatarev-update", "project-dashboard-update", "project-delete", "project-deliverablerev-create", "project-deliverablerev-delete", "project-deliverablerev-index", "project-deliverablerev-update", "project-deliverablerev-view", "project-designdatarev-create", "project-designdatarev-delete", "project-designdatarev-index", "project-designdatarev-update", "project-designdatarev-view", "project-index", "project-report", "project-update", "project-view", "regulation-create", "regulation-delete", "regulation-index", "regulation-update", "regulation-view", "report-list-gcp", "report-list-pm", "serialnumber-create", "serialnumber-delete", "serialnumber-index", "serialnumber-update", "serialnumber-view", "show-hidden-field", "subpart-create", "subpart-delete", "subpart-index", "subpart-update", "subpart-view", "subsection-create", "subsection-delete", "subsection-index", "subsection-update", "subsection-view", "task-create", "task-delete", "task-index", "task-update", "task-view", "tccadocstatus-create", "tccadocstatus-delete", "tccadocstatus-index", "tccadocstatus-update", "tccadocstatus-view", "tccaproject-associate", "tccaproject-create", "tccaproject-dashboard", "tccaproject-dashboard-update", "tccaproject-delete", "tccaproject-deliverablerev-create", "tccaproject-deliverablerev-delete", "tccaproject-deliverablerev-index", "tccaproject-deliverablerev-update", "tccaproject-deliverablerev-view", "tccaproject-index", "tccaproject-project-create", "tccaproject-project-delete", "tccaproject-project-index", "tccaproject-project-update", "tccaproject-project-view", "tccaproject-update", "tccaproject-view"], childRoleIds: ["Elisen - Supervisor"] },
  { id: "Elisen - Project Group", name: "Elisen - Project Group", description: "Elisen - Project Group", permissionIds: ["aircraft-create", "aircraft-index", "aircraft-update", "aircraft-view", "approval-create", "approval-dashboard", "approval-dashboard-update", "approval-index", "approval-serialnumber-create", "approval-serialnumber-index", "approval-serialnumber-update", "approval-serialnumber-view", "approval-update", "approval-view", "approvalissue-create", "approvalissue-index", "approvalissue-update", "approvalissue-view", "atachapter-create", "atachapter-update", "atasubchapter-create", "atasubchapter-update", "certbasis-copy", "certbasis-create", "certbasis-delete", "certbasis-edit", "certbasis-import", "certbasis-index", "certbasis-update", "certbasis-view", "certplan-copy", "certplan-create", "certplan-dashboard", "certplan-delete", "certplan-index", "certplan-initialize", "certplan-update", "certplan-view", "checklist-create", "checklist-index", "checklist-update", "checklist-view", "company-create", "company-index", "company-update", "company-view", "contact-create", "contact-index", "contact-update", "contact-view", "dds-create", "dds-delete", "dds-index", "dds-update", "dds-view", "delegation-create", "delegation-delete", "delegation-index", "delegation-update", "delegation-view", "deliverable-create", "deliverable-index", "deliverable-update", "deliverable-view", "deliverablerev-create", "deliverablerev-index", "deliverablerev-update", "deliverablerev-view", "designdata-create", "designdata-index", "designdata-update", "designdata-view", "designdatarev-create", "designdatarev-index", "designdatarev-update", "designdatarev-view", "discipline-create", "discipline-delete", "discipline-index", "discipline-update", "discipline-view", "foc-create", "foc-delete", "foc-index", "foc-update", "foc-view", "gcp-copy", "gcp-create", "gcp-dashboard", "gcp-dashboard-tab-update", "gcp-dashboard-update", "gcp-delete", "gcp-index", "gcp-menu", "gcp-modify", "gcp-update", "gcp-view", "mastercertbasis-create", "mastercertbasis-delete", "mastercertbasis-index", "mastercertbasis-update", "mastercertbasis-view", "moc-create", "moc-delete", "moc-index", "moc-update", "moc-view", "project-aircraft-create", "project-aircraft-index", "project-aircraft-update", "project-aircraft-view", "project-approval-create", "project-approval-index", "project-approval-update", "project-approval-view", "project-create", "project-dashboard", "project-dashboard-update", "project-designdatarev-create", "project-index", "project-report", "project-review", "project-review-tab-1", "project-review-tab-2", "project-review-tab-3", "project-review-tab-3-hours", "project-review-tab-4", "project-review-tab-5", "project-review-tab-6", "project-review-tab-7", "project-review-tab-8", "project-update", "project-view", "regulation-checklist", "regulation-copy", "regulation-create", "regulation-delete", "regulation-index", "regulation-selectchecklist", "regulation-update", "regulation-view", "regulationgroup-create", "regulationgroup-delete", "regulationgroup-index", "regulationgroup-update", "regulationgroup-view", "regulationgroupsection-create", "regulationgroupsection-delete", "regulationgroupsection-edit", "regulationgroupsection-index", "regulationgroupsection-update", "regulationgroupsection-view", "report-list-gcp", "serialnumber-create", "serialnumber-index", "serialnumber-update", "serialnumber-view", "subpart-create", "subpart-delete", "subpart-index", "subpart-update", "subpart-view", "subsection-create", "subsection-delete", "subsection-index", "subsection-update", "subsection-view", "tccadocstatus-create", "tccadocstatus-index", "tccadocstatus-update", "tccadocstatus-view", "tccaproject-create", "tccaproject-dashboard", "tccaproject-dashboard-update", "tccaproject-deliverablerev-create", "tccaproject-deliverablerev-index", "tccaproject-deliverablerev-update", "tccaproject-deliverablerev-view", "tccaproject-index", "tccaproject-project-create", "tccaproject-project-index", "tccaproject-project-update", "tccaproject-project-view", "tccaproject-update", "tccaproject-view"], childRoleIds: ["Elisen - Employee"] },
  { id: "Elisen - Specialist", name: "Elisen - Specialist", description: "Elisen - Specialist", permissionIds: [], childRoleIds: [] },
  { id: "Elisen - Supervisor", name: "Elisen - Supervisor", description: "Elisen - Supervisor", permissionIds: [], childRoleIds: ["Elisen - Project Group"] },
  { id: "Sysadmin", name: "Sysadmin", description: "System Administrator", permissionIds: ["audit", "beta-performance", "report-create", "report-delete", "report-index", "report-update", "report-view"], childRoleIds: ["Elisen - Admin"] },
]

export const ACCESS_USERS: AccessUser[] = [
  { id: "u-2", username: "adrian.bergstrom", email: "adrian.bergstrom@elisen.example", status: "active", roleIds: ["Sysadmin"], directPermissionIds: [] },
  { id: "u-10", username: "alma.devereaux", email: "alma.devereaux@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-11", username: "anders.hartmann", email: "anders.hartmann@elisen.example", status: "active", roleIds: ["Elisen - Admin"], directPermissionIds: [] },
  { id: "u-12", username: "anika.nakamura", email: "anika.nakamura@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-13", username: "arjun.rasmussen", email: "arjun.rasmussen@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-14", username: "astrid.solberg", email: "astrid.solberg@elisen.example", status: "active", roleIds: ["Elisen - Admin"], directPermissionIds: [] },
  { id: "u-15", username: "aurelie.whitlock", email: "aurelie.whitlock@elisen.example", status: "active", roleIds: ["Elisen - Manager"], directPermissionIds: [] },
  { id: "u-16", username: "bilal.bergstrom", email: "bilal.bergstrom@elisen.example", status: "active", roleIds: ["Elisen - Manager"], directPermissionIds: [] },
  { id: "u-17", username: "bram.devereaux", email: "bram.devereaux@elisen.example", status: "active", roleIds: ["Elisen - Manager"], directPermissionIds: [] },
  { id: "u-18", username: "camille.hartmann", email: "camille.hartmann@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-19", username: "cato.nakamura", email: "cato.nakamura@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-20", username: "cedric.rasmussen", email: "cedric.rasmussen@elisen.example", status: "active", roleIds: ["Elisen - Project Group"], directPermissionIds: [] },
  { id: "u-21", username: "chiara.solberg", email: "chiara.solberg@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-22", username: "clara.whitlock", email: "clara.whitlock@elisen.example", status: "active", roleIds: ["Elisen - Manager"], directPermissionIds: [] },
  { id: "u-23", username: "damien.bergstrom", email: "damien.bergstrom@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-24", username: "dara.devereaux", email: "dara.devereaux@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-25", username: "delphine.hartmann", email: "delphine.hartmann@elisen.example", status: "active", roleIds: ["Elisen - Project Group"], directPermissionIds: [] },
  { id: "u-26", username: "dmitri.nakamura", email: "dmitri.nakamura@elisen.example", status: "active", roleIds: ["Elisen - Admin"], directPermissionIds: [] },
  { id: "u-27", username: "eleni.rasmussen", email: "eleni.rasmussen@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-28", username: "elias.solberg", email: "elias.solberg@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-29", username: "esme.whitlock", email: "esme.whitlock@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-30", username: "ewan.bergstrom", email: "ewan.bergstrom@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-31", username: "fabien.devereaux", email: "fabien.devereaux@elisen.example", status: "active", roleIds: ["Client - Manager"], directPermissionIds: [] },
  { id: "u-32", username: "farida.hartmann", email: "farida.hartmann@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-33", username: "felix.nakamura", email: "felix.nakamura@elisen.example", status: "active", roleIds: ["Client - Manager"], directPermissionIds: [] },
  { id: "u-34", username: "fiona.rasmussen", email: "fiona.rasmussen@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-35", username: "gabriel.solberg", email: "gabriel.solberg@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-36", username: "georgia.whitlock", email: "georgia.whitlock@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-37", username: "gustav.bergstrom", email: "gustav.bergstrom@elisen.example", status: "active", roleIds: ["Elisen - Project Group"], directPermissionIds: [] },
  { id: "u-38", username: "hana.devereaux", email: "hana.devereaux@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-39", username: "hugo.hartmann", email: "hugo.hartmann@elisen.example", status: "active", roleIds: ["Elisen - Project Group"], directPermissionIds: [] },
  { id: "u-40", username: "ilya.nakamura", email: "ilya.nakamura@elisen.example", status: "active", roleIds: ["Elisen - Project Group"], directPermissionIds: [] },
  { id: "u-41", username: "imani.rasmussen", email: "imani.rasmussen@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-42", username: "ingrid.solberg", email: "ingrid.solberg@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-43", username: "iris.whitlock", email: "iris.whitlock@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-44", username: "jonas.bergstrom", email: "jonas.bergstrom@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-45", username: "joris.devereaux", email: "joris.devereaux@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-46", username: "juliette.hartmann", email: "juliette.hartmann@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-47", username: "kai.nakamura", email: "kai.nakamura@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-50", username: "karim.rasmussen", email: "karim.rasmussen@elisen.example", status: "active", roleIds: ["Elisen - Manager"], directPermissionIds: [] },
  { id: "u-51", username: "katya.solberg", email: "katya.solberg@elisen.example", status: "active", roleIds: ["Elisen - Manager"], directPermissionIds: [] },
  { id: "u-52", username: "lars.whitlock", email: "lars.whitlock@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-53", username: "leila.bergstrom", email: "leila.bergstrom@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-54", username: "lena.devereaux", email: "lena.devereaux@elisen.example", status: "active", roleIds: ["Client - Manager"], directPermissionIds: [] },
  { id: "u-55", username: "lucas.hartmann", email: "lucas.hartmann@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-56", username: "maeve.nakamura", email: "maeve.nakamura@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-57", username: "magnus.rasmussen", email: "magnus.rasmussen@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-58", username: "malik.solberg", email: "malik.solberg@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-59", username: "marek.whitlock", email: "marek.whitlock@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-60", username: "mariam.bergstrom", email: "mariam.bergstrom@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-61", username: "mateo.devereaux", email: "mateo.devereaux@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-62", username: "mira.hartmann", email: "mira.hartmann@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-63", username: "nadia.nakamura", email: "nadia.nakamura@elisen.example", status: "active", roleIds: ["Elisen - Project Group"], directPermissionIds: [] },
  { id: "u-64", username: "nils.rasmussen", email: "nils.rasmussen@elisen.example", status: "active", roleIds: ["Elisen - Manager"], directPermissionIds: [] },
  { id: "u-65", username: "noor.solberg", email: "noor.solberg@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-66", username: "olivier.whitlock", email: "olivier.whitlock@elisen.example", status: "active", roleIds: ["Sysadmin"], directPermissionIds: [] },
  { id: "u-67", username: "oskar.bergstrom", email: "oskar.bergstrom@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-68", username: "petra.devereaux", email: "petra.devereaux@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-69", username: "quentin.hartmann", email: "quentin.hartmann@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-70", username: "rafael.nakamura", email: "rafael.nakamura@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-72", username: "raisa.rasmussen", email: "raisa.rasmussen@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-73", username: "reza.solberg", email: "reza.solberg@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-74", username: "rosa.whitlock", email: "rosa.whitlock@elisen.example", status: "active", roleIds: ["Client - Employee"], directPermissionIds: [] },
  { id: "u-75", username: "rune.bergstrom", email: "rune.bergstrom@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
  { id: "u-76", username: "sabine.devereaux", email: "sabine.devereaux@elisen.example", status: "active", roleIds: ["Elisen - Employee"], directPermissionIds: [] },
]
