import type { Approval, ApprovalRevision, DocRevision, ProjectDocument, ProjectRevisionLink } from '@/types/documents'

/** Obviously-fake demo data. Revision ids rev-1..rev-7 are stable — the TCCA
    document links in tccaFixtures reference them. */

export const DOCUMENTS: ProjectDocument[] = [
  { id: 'doc-1', kind: 'deliverable', number: 'COM-3200', title: 'Certification Plan: Cabin Interior Mod', type: 'Plan', owner: 'Kelly Osei' },
  { id: 'doc-2', kind: 'deliverable', number: 'ELA-3200', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Remi Rocheleau' },
  { id: 'doc-3', kind: 'deliverable', number: 'DCR-3200', title: 'Design Compliance Report', type: 'Report', owner: 'Kelly Osei' },
  { id: 'doc-4', kind: 'deliverable', number: 'MDL-3200', title: 'Master Data List', type: 'Report', owner: 'Sofia Reyes' },
  { id: 'doc-5', kind: 'deliverable', number: 'COM-3201', title: 'Certification Plan: Map Light Addition', type: 'Plan', owner: 'Harris Bell' },
  { id: 'doc-6', kind: 'deliverable', number: 'FTP-3201', title: 'Flight Test Plan', type: 'Plan', owner: 'Lloyd Pedvis' },
  { id: 'doc-7', kind: 'deliverable', number: 'WBR-3203', title: 'Weight & Balance Report', type: 'Report', owner: 'Remi Rocheleau' },
  { id: 'doc-8', kind: 'drawing', number: 'DRW-3200-101', title: 'Seat Installation: LH Club', type: 'Installation', owner: 'Sofia Reyes', aircraft: 'King Air 350', ataChapter: '25-20' },
  { id: 'doc-9', kind: 'drawing', number: 'DRW-3200-102', title: 'Folding Table Assembly', type: 'Assembly', owner: 'Sofia Reyes', aircraft: 'King Air 350', ataChapter: '25-20' },
  { id: 'doc-10', kind: 'drawing', number: 'DRW-2018-044', title: 'iPad Holder Bracket', type: 'Detail', owner: 'Lloyd Pedvis', aircraft: 'B737-800', ataChapter: '25-10' },

  // Generated so every project that has started work has real
  // deliverables and drawings to show. RFQ-stage projects get none —
  // nothing has been produced before award, and an empty tab is the
  // honest answer there.
  { id: 'doc-g0-0', kind: 'deliverable', number: 'COM-3202', title: 'Certification Plan', type: 'Plan', owner: 'Sofia Reyes' },
  { id: 'doc-g0-1', kind: 'deliverable', number: 'DCR-3202', title: 'Design Compliance Report', type: 'Report', owner: 'Sofia Reyes' },
  { id: 'doc-gd0-0', kind: 'drawing', number: 'DRW-3202-101', title: 'Installation Drawing', type: 'Installation', owner: 'Sofia Reyes', aircraft: 'A-4N Skyhawk', ataChapter: '25-20' },
  { id: 'doc-g1-0', kind: 'deliverable', number: 'DCR-3205', title: 'Design Compliance Report', type: 'Report', owner: 'Harris Bell' },
  { id: 'doc-g1-1', kind: 'deliverable', number: 'MDL-3205', title: 'Master Data List', type: 'Report', owner: 'Harris Bell' },
  { id: 'doc-g1-2', kind: 'deliverable', number: 'ELA-3205', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Harris Bell' },
  { id: 'doc-gd1-0', kind: 'drawing', number: 'DRW-3205-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Harris Bell', aircraft: 'Not aircraft-specific', ataChapter: '25-10' },
  { id: 'doc-gd1-1', kind: 'drawing', number: 'DRW-3205-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Harris Bell', aircraft: 'Not aircraft-specific', ataChapter: '92-00' },
  { id: 'doc-g2-0', kind: 'deliverable', number: 'MDL-3277', title: 'Master Data List', type: 'Report', owner: 'Lloyd Pedvis' },
  { id: 'doc-g2-1', kind: 'deliverable', number: 'ELA-3277', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Lloyd Pedvis' },
  { id: 'doc-g2-2', kind: 'deliverable', number: 'SAR-3277', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Lloyd Pedvis' },
  { id: 'doc-g2-3', kind: 'deliverable', number: 'ICA-3277', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Lloyd Pedvis' },
  { id: 'doc-gd2-0', kind: 'drawing', number: 'DRW-3277-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Lloyd Pedvis', aircraft: 'Challenger 650', ataChapter: '92-00' },
  { id: 'doc-g3-0', kind: 'deliverable', number: 'ELA-3282', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Remi Rocheleau' },
  { id: 'doc-g3-1', kind: 'deliverable', number: 'SAR-3282', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Remi Rocheleau' },
  { id: 'doc-gd3-0', kind: 'drawing', number: 'DRW-3282-101', title: 'Installation Drawing', type: 'Installation', owner: 'Remi Rocheleau', aircraft: 'Twin Otter 300', ataChapter: '25-20' },
  { id: 'doc-gd3-1', kind: 'drawing', number: 'DRW-3282-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Remi Rocheleau', aircraft: 'Twin Otter 300', ataChapter: '25-10' },
  { id: 'doc-g4-0', kind: 'deliverable', number: 'SAR-3284', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Kelly Osei' },
  { id: 'doc-g4-1', kind: 'deliverable', number: 'ICA-3284', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Kelly Osei' },
  { id: 'doc-g4-2', kind: 'deliverable', number: 'COM-3284', title: 'Certification Plan', type: 'Plan', owner: 'Kelly Osei' },
  { id: 'doc-gd4-0', kind: 'drawing', number: 'DRW-3284-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Kelly Osei', aircraft: 'A330-300', ataChapter: '25-10' },
  { id: 'doc-g5-0', kind: 'deliverable', number: 'ICA-3291', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Harris Bell' },
  { id: 'doc-g5-1', kind: 'deliverable', number: 'COM-3291', title: 'Certification Plan', type: 'Plan', owner: 'Harris Bell' },
  { id: 'doc-g5-2', kind: 'deliverable', number: 'DCR-3291', title: 'Design Compliance Report', type: 'Report', owner: 'Harris Bell' },
  { id: 'doc-g5-3', kind: 'deliverable', number: 'MDL-3291', title: 'Master Data List', type: 'Report', owner: 'Harris Bell' },
  { id: 'doc-gd5-0', kind: 'drawing', number: 'DRW-3291-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Harris Bell', aircraft: 'B737-700', ataChapter: '92-00' },
  { id: 'doc-gd5-1', kind: 'drawing', number: 'DRW-3291-101', title: 'Installation Drawing', type: 'Installation', owner: 'Harris Bell', aircraft: 'B737-700', ataChapter: '25-20' },
  { id: 'doc-g6-0', kind: 'deliverable', number: 'COM-3107', title: 'Certification Plan', type: 'Plan', owner: 'Sofia Reyes' },
  { id: 'doc-g6-1', kind: 'deliverable', number: 'DCR-3107', title: 'Design Compliance Report', type: 'Report', owner: 'Sofia Reyes' },
  { id: 'doc-gd6-0', kind: 'drawing', number: 'DRW-3107-101', title: 'Installation Drawing', type: 'Installation', owner: 'Sofia Reyes', aircraft: 'Learjet 45', ataChapter: '25-20' },
  { id: 'doc-g7-0', kind: 'deliverable', number: 'DCR-3116', title: 'Design Compliance Report', type: 'Report', owner: 'Lloyd Pedvis' },
  { id: 'doc-g7-1', kind: 'deliverable', number: 'MDL-3116', title: 'Master Data List', type: 'Report', owner: 'Lloyd Pedvis' },
  { id: 'doc-g7-2', kind: 'deliverable', number: 'ELA-3116', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Lloyd Pedvis' },
  { id: 'doc-gd7-0', kind: 'drawing', number: 'DRW-3116-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Lloyd Pedvis', aircraft: 'ATR 72-600', ataChapter: '25-10' },
  { id: 'doc-gd7-1', kind: 'drawing', number: 'DRW-3116-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Lloyd Pedvis', aircraft: 'ATR 72-600', ataChapter: '92-00' },
  { id: 'doc-g8-0', kind: 'deliverable', number: 'MDL-3116', title: 'Master Data List', type: 'Report', owner: 'Remi Rocheleau' },
  { id: 'doc-g8-1', kind: 'deliverable', number: 'ELA-3116', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Remi Rocheleau' },
  { id: 'doc-g8-2', kind: 'deliverable', number: 'SAR-3116', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Remi Rocheleau' },
  { id: 'doc-g8-3', kind: 'deliverable', number: 'ICA-3116', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Remi Rocheleau' },
  { id: 'doc-gd8-0', kind: 'drawing', number: 'DRW-3116-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Remi Rocheleau', aircraft: 'PC-12 NGX', ataChapter: '92-00' },
  { id: 'doc-g9-0', kind: 'deliverable', number: 'ELA-3292', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Kelly Osei' },
  { id: 'doc-g9-1', kind: 'deliverable', number: 'SAR-3292', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Kelly Osei' },
  { id: 'doc-gd9-0', kind: 'drawing', number: 'DRW-3292-101', title: 'Installation Drawing', type: 'Installation', owner: 'Kelly Osei', aircraft: 'Citation Latitude', ataChapter: '25-20' },
  { id: 'doc-gd9-1', kind: 'drawing', number: 'DRW-3292-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Kelly Osei', aircraft: 'Citation Latitude', ataChapter: '25-10' },
  { id: 'doc-g10-0', kind: 'deliverable', number: 'SAR-3293', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Harris Bell' },
  { id: 'doc-g10-1', kind: 'deliverable', number: 'ICA-3293', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Harris Bell' },
  { id: 'doc-g10-2', kind: 'deliverable', number: 'COM-3293', title: 'Certification Plan', type: 'Plan', owner: 'Harris Bell' },
  { id: 'doc-gd10-0', kind: 'drawing', number: 'DRW-3293-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Harris Bell', aircraft: 'Dash 8-400', ataChapter: '25-10' },
  { id: 'doc-g11-0', kind: 'deliverable', number: 'ICA-3294', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Sofia Reyes' },
  { id: 'doc-g11-1', kind: 'deliverable', number: 'COM-3294', title: 'Certification Plan', type: 'Plan', owner: 'Sofia Reyes' },
  { id: 'doc-g11-2', kind: 'deliverable', number: 'DCR-3294', title: 'Design Compliance Report', type: 'Report', owner: 'Sofia Reyes' },
  { id: 'doc-g11-3', kind: 'deliverable', number: 'MDL-3294', title: 'Master Data List', type: 'Report', owner: 'Sofia Reyes' },
  { id: 'doc-gd11-0', kind: 'drawing', number: 'DRW-3294-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Sofia Reyes', aircraft: 'CRJ200', ataChapter: '92-00' },
  { id: 'doc-gd11-1', kind: 'drawing', number: 'DRW-3294-101', title: 'Installation Drawing', type: 'Installation', owner: 'Sofia Reyes', aircraft: 'CRJ200', ataChapter: '25-20' },
  { id: 'doc-g12-0', kind: 'deliverable', number: 'COM-3295', title: 'Certification Plan', type: 'Plan', owner: 'Lloyd Pedvis' },
  { id: 'doc-g12-1', kind: 'deliverable', number: 'DCR-3295', title: 'Design Compliance Report', type: 'Report', owner: 'Lloyd Pedvis' },
  { id: 'doc-gd12-0', kind: 'drawing', number: 'DRW-3295-101', title: 'Installation Drawing', type: 'Installation', owner: 'Lloyd Pedvis', aircraft: 'Global Express', ataChapter: '25-20' },
  { id: 'doc-g13-0', kind: 'deliverable', number: 'DCR-3261', title: 'Design Compliance Report', type: 'Report', owner: 'Remi Rocheleau' },
  { id: 'doc-g13-1', kind: 'deliverable', number: 'MDL-3261', title: 'Master Data List', type: 'Report', owner: 'Remi Rocheleau' },
  { id: 'doc-g13-2', kind: 'deliverable', number: 'ELA-3261', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Remi Rocheleau' },
  { id: 'doc-gd13-0', kind: 'drawing', number: 'DRW-3261-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Remi Rocheleau', aircraft: 'King Air 350', ataChapter: '25-10' },
  { id: 'doc-gd13-1', kind: 'drawing', number: 'DRW-3261-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Remi Rocheleau', aircraft: 'King Air 350', ataChapter: '92-00' },
  { id: 'doc-g14-0', kind: 'deliverable', number: 'MDL-3262', title: 'Master Data List', type: 'Report', owner: 'Kelly Osei' },
  { id: 'doc-g14-1', kind: 'deliverable', number: 'ELA-3262', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Kelly Osei' },
  { id: 'doc-g14-2', kind: 'deliverable', number: 'SAR-3262', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Kelly Osei' },
  { id: 'doc-g14-3', kind: 'deliverable', number: 'ICA-3262', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Kelly Osei' },
  { id: 'doc-gd14-0', kind: 'drawing', number: 'DRW-3262-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Kelly Osei', aircraft: 'Challenger 650', ataChapter: '92-00' },
  { id: 'doc-g15-0', kind: 'deliverable', number: 'ELA-3262', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Harris Bell' },
  { id: 'doc-g15-1', kind: 'deliverable', number: 'SAR-3262', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Harris Bell' },
  { id: 'doc-gd15-0', kind: 'drawing', number: 'DRW-3262-101', title: 'Installation Drawing', type: 'Installation', owner: 'Harris Bell', aircraft: 'Twin Otter 300', ataChapter: '25-20' },
  { id: 'doc-gd15-1', kind: 'drawing', number: 'DRW-3262-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Harris Bell', aircraft: 'Twin Otter 300', ataChapter: '25-10' },
  { id: 'doc-g16-0', kind: 'deliverable', number: 'SAR-3262', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Sofia Reyes' },
  { id: 'doc-g16-1', kind: 'deliverable', number: 'ICA-3262', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Sofia Reyes' },
  { id: 'doc-g16-2', kind: 'deliverable', number: 'COM-3262', title: 'Certification Plan', type: 'Plan', owner: 'Sofia Reyes' },
  { id: 'doc-gd16-0', kind: 'drawing', number: 'DRW-3262-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Sofia Reyes', aircraft: 'A330-300', ataChapter: '25-10' },
  { id: 'doc-g17-0', kind: 'deliverable', number: 'ICA-3275', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Lloyd Pedvis' },
  { id: 'doc-g17-1', kind: 'deliverable', number: 'COM-3275', title: 'Certification Plan', type: 'Plan', owner: 'Lloyd Pedvis' },
  { id: 'doc-g17-2', kind: 'deliverable', number: 'DCR-3275', title: 'Design Compliance Report', type: 'Report', owner: 'Lloyd Pedvis' },
  { id: 'doc-g17-3', kind: 'deliverable', number: 'MDL-3275', title: 'Master Data List', type: 'Report', owner: 'Lloyd Pedvis' },
  { id: 'doc-gd17-0', kind: 'drawing', number: 'DRW-3275-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Lloyd Pedvis', aircraft: 'B737-700', ataChapter: '92-00' },
  { id: 'doc-gd17-1', kind: 'drawing', number: 'DRW-3275-101', title: 'Installation Drawing', type: 'Installation', owner: 'Lloyd Pedvis', aircraft: 'B737-700', ataChapter: '25-20' },
  { id: 'doc-g18-0', kind: 'deliverable', number: 'COM-3276', title: 'Certification Plan', type: 'Plan', owner: 'Remi Rocheleau' },
  { id: 'doc-g18-1', kind: 'deliverable', number: 'DCR-3276', title: 'Design Compliance Report', type: 'Report', owner: 'Remi Rocheleau' },
  { id: 'doc-gd18-0', kind: 'drawing', number: 'DRW-3276-101', title: 'Installation Drawing', type: 'Installation', owner: 'Remi Rocheleau', aircraft: 'Learjet 45', ataChapter: '25-20' },
  { id: 'doc-g19-0', kind: 'deliverable', number: 'DCR-3289', title: 'Design Compliance Report', type: 'Report', owner: 'Kelly Osei' },
  { id: 'doc-g19-1', kind: 'deliverable', number: 'MDL-3289', title: 'Master Data List', type: 'Report', owner: 'Kelly Osei' },
  { id: 'doc-g19-2', kind: 'deliverable', number: 'ELA-3289', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Kelly Osei' },
  { id: 'doc-gd19-0', kind: 'drawing', number: 'DRW-3289-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Kelly Osei', aircraft: 'ATR 72-600', ataChapter: '25-10' },
  { id: 'doc-gd19-1', kind: 'drawing', number: 'DRW-3289-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Kelly Osei', aircraft: 'ATR 72-600', ataChapter: '92-00' },
  { id: 'doc-g20-0', kind: 'deliverable', number: 'MDL-0000', title: 'Master Data List', type: 'Report', owner: 'Harris Bell' },
  { id: 'doc-g20-1', kind: 'deliverable', number: 'ELA-0000', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Harris Bell' },
  { id: 'doc-g20-2', kind: 'deliverable', number: 'SAR-0000', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Harris Bell' },
  { id: 'doc-g20-3', kind: 'deliverable', number: 'ICA-0000', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Harris Bell' },
  { id: 'doc-gd20-0', kind: 'drawing', number: 'DRW-0000-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Harris Bell', aircraft: 'PC-12 NGX', ataChapter: '92-00' },
  { id: 'doc-g21-0', kind: 'deliverable', number: 'ELA-0000', title: 'Electrical Load Analysis', type: 'Analysis', owner: 'Sofia Reyes' },
  { id: 'doc-g21-1', kind: 'deliverable', number: 'SAR-0000', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Sofia Reyes' },
  { id: 'doc-gd21-0', kind: 'drawing', number: 'DRW-0000-101', title: 'Installation Drawing', type: 'Installation', owner: 'Sofia Reyes', aircraft: 'Citation Latitude', ataChapter: '25-20' },
  { id: 'doc-gd21-1', kind: 'drawing', number: 'DRW-0000-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Sofia Reyes', aircraft: 'Citation Latitude', ataChapter: '25-10' },
  { id: 'doc-g22-0', kind: 'deliverable', number: 'SAR-0000', title: 'Structural Analysis Report', type: 'Analysis', owner: 'Lloyd Pedvis' },
  { id: 'doc-g22-1', kind: 'deliverable', number: 'ICA-0000', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Lloyd Pedvis' },
  { id: 'doc-g22-2', kind: 'deliverable', number: 'COM-0000', title: 'Certification Plan', type: 'Plan', owner: 'Lloyd Pedvis' },
  { id: 'doc-gd22-0', kind: 'drawing', number: 'DRW-0000-102', title: 'Assembly Drawing', type: 'Assembly', owner: 'Lloyd Pedvis', aircraft: 'Dash 8-400', ataChapter: '25-10' },
  { id: 'doc-g23-0', kind: 'deliverable', number: 'ICA-0000', title: 'Instructions for Continued Airworthiness', type: 'Report', owner: 'Remi Rocheleau' },
  { id: 'doc-g23-1', kind: 'deliverable', number: 'COM-0000', title: 'Certification Plan', type: 'Plan', owner: 'Remi Rocheleau' },
  { id: 'doc-g23-2', kind: 'deliverable', number: 'DCR-0000', title: 'Design Compliance Report', type: 'Report', owner: 'Remi Rocheleau' },
  { id: 'doc-g23-3', kind: 'deliverable', number: 'MDL-0000', title: 'Master Data List', type: 'Report', owner: 'Remi Rocheleau' },
  { id: 'doc-gd23-0', kind: 'drawing', number: 'DRW-0000-201', title: 'Wiring Diagram', type: 'Detail', owner: 'Remi Rocheleau', aircraft: 'CRJ200', ataChapter: '92-00' },
  { id: 'doc-gd23-1', kind: 'drawing', number: 'DRW-0000-101', title: 'Installation Drawing', type: 'Installation', owner: 'Remi Rocheleau', aircraft: 'CRJ200', ataChapter: '25-20' },
  { id: 'doc-g24-0', kind: 'deliverable', number: 'COM-0000', title: 'Certification Plan', type: 'Plan', owner: 'Kelly Osei' },
  { id: 'doc-g24-1', kind: 'deliverable', number: 'DCR-0000', title: 'Design Compliance Report', type: 'Report', owner: 'Kelly Osei' },
  { id: 'doc-gd24-0', kind: 'drawing', number: 'DRW-0000-101', title: 'Installation Drawing', type: 'Installation', owner: 'Kelly Osei', aircraft: 'Global Express', ataChapter: '25-20' },
]

export const DOC_REVISIONS: DocRevision[] = [
  { id: 'rev-1', documentId: 'doc-1', rev: 'A', initialProjectId: '1', openedDate: '2026-04-10', dueDate: '2026-05-01', releasedDate: '2026-05-04', receivedDate: '2026-05-20', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'accepted' },
  { id: 'rev-2', documentId: 'doc-2', rev: 'B', initialProjectId: '1', openedDate: '2026-06-01', dueDate: '2026-06-20', releasedDate: '2026-06-11', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'in-review' },
  { id: 'rev-2a', documentId: 'doc-2', rev: 'A', initialProjectId: '2', openedDate: '2025-12-01', dueDate: '2026-01-15', releasedDate: '2026-01-10', receivedDate: '2026-01-20', closedDate: '2026-02-01', nextAction: '—', url: '', status: 'superseded' },
  { id: 'rev-3', documentId: 'doc-3', rev: 'A', initialProjectId: '1', openedDate: '2026-06-25', dueDate: '2026-08-15', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'wip' },
  { id: 'rev-4', documentId: 'doc-4', rev: 'A', initialProjectId: '1', openedDate: '2026-06-20', dueDate: '2026-07-10', releasedDate: '2026-06-28', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'signature' },
  { id: 'rev-5', documentId: 'doc-5', rev: 'A', initialProjectId: '2', openedDate: '2025-12-05', dueDate: '2026-01-10', releasedDate: '2026-03-19', receivedDate: '2026-03-27', closedDate: '2026-03-27', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-6', documentId: 'doc-6', rev: 'C', initialProjectId: '2', openedDate: '2026-02-01', dueDate: '2026-03-01', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'wip' },
  { id: 'rev-7', documentId: 'doc-7', rev: 'A', initialProjectId: '4', openedDate: '2026-07-01', dueDate: '2026-08-30', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'wip' },
  { id: 'rev-8', documentId: 'doc-8', rev: 'A', initialProjectId: '1', openedDate: '2026-05-12', dueDate: '2026-07-01', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'in-review' },
  { id: 'rev-9', documentId: 'doc-9', rev: 'B', initialProjectId: '1', openedDate: '2026-04-02', dueDate: '2026-05-15', releasedDate: '2026-05-10', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-10', documentId: 'doc-10', rev: 'A', initialProjectId: '5', openedDate: '2024-03-04', dueDate: '2024-04-01', releasedDate: '2024-04-11', receivedDate: '', closedDate: '2024-05-01', nextAction: '—', url: '', status: 'accepted' },

  { id: 'rev-g0-0', documentId: 'doc-g0-0', rev: 'A', initialProjectId: '3', openedDate: '2026-02-21', dueDate: '2026-04-02', releasedDate: '2026-03-28', receivedDate: '2026-04-12', closedDate: '2026-04-17', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g0-1', documentId: 'doc-g0-1', rev: 'B', initialProjectId: '3', openedDate: '2026-03-08', dueDate: '2026-04-22', releasedDate: '2026-04-15', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'in-review' },
  { id: 'rev-gd0-0', documentId: 'doc-gd0-0', rev: 'A', initialProjectId: '3', openedDate: '2026-03-03', dueDate: '2026-04-22', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'wip' },
  { id: 'rev-g1-0', documentId: 'doc-g1-0', rev: 'A', initialProjectId: '6', openedDate: '2026-02-04', dueDate: '2026-03-16', releasedDate: '2026-03-11', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'in-review' },
  { id: 'rev-g1-1', documentId: 'doc-g1-1', rev: 'B', initialProjectId: '6', openedDate: '2026-02-19', dueDate: '2026-04-05', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'wip' },
  { id: 'rev-g1-2', documentId: 'doc-g1-2', rev: 'C', initialProjectId: '6', openedDate: '2026-03-06', dueDate: '2026-04-25', releasedDate: '2026-04-16', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'signature' },
  { id: 'rev-gd1-0', documentId: 'doc-gd1-0', rev: 'A', initialProjectId: '6', openedDate: '2026-02-14', dueDate: '2026-04-05', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'signature' },
  { id: 'rev-gd1-1', documentId: 'doc-gd1-1', rev: 'B', initialProjectId: '6', openedDate: '2026-02-26', dueDate: '2026-04-17', releasedDate: '2026-04-12', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g2-0', documentId: 'doc-g2-0', rev: 'A', initialProjectId: 'rv-748', openedDate: '2026-03-21', dueDate: '2026-04-30', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'wip' },
  { id: 'rev-g2-1', documentId: 'doc-g2-1', rev: 'B', initialProjectId: 'rv-748', openedDate: '2026-04-05', dueDate: '2026-05-20', releasedDate: '2026-05-13', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'signature' },
  { id: 'rev-g2-2', documentId: 'doc-g2-2', rev: 'C', initialProjectId: 'rv-748', openedDate: '2026-04-20', dueDate: '2026-06-09', releasedDate: '2026-05-31', receivedDate: '2026-06-15', closedDate: '2026-06-20', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g2-3', documentId: 'doc-g2-3', rev: 'A', initialProjectId: 'rv-748', openedDate: '2026-05-05', dueDate: '2026-06-29', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'wip' },
  { id: 'rev-gd2-0', documentId: 'doc-gd2-0', rev: 'A', initialProjectId: 'rv-748', openedDate: '2026-03-31', dueDate: '2026-05-20', releasedDate: '2026-05-15', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g3-0', documentId: 'doc-g3-0', rev: 'A', initialProjectId: 'rv-770', openedDate: '2026-04-07', dueDate: '2026-05-17', releasedDate: '2026-05-12', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'signature' },
  { id: 'rev-g3-1', documentId: 'doc-g3-1', rev: 'B', initialProjectId: 'rv-770', openedDate: '2026-04-22', dueDate: '2026-06-06', releasedDate: '2026-05-30', receivedDate: '2026-06-14', closedDate: '2026-06-19', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-gd3-0', documentId: 'doc-gd3-0', rev: 'A', initialProjectId: 'rv-770', openedDate: '2026-04-17', dueDate: '2026-06-06', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'wip' },
  { id: 'rev-gd3-1', documentId: 'doc-gd3-1', rev: 'B', initialProjectId: 'rv-770', openedDate: '2026-04-29', dueDate: '2026-06-18', releasedDate: '2026-06-13', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g4-0', documentId: 'doc-g4-0', rev: 'A', initialProjectId: 'rv-755', openedDate: '2025-06-28', dueDate: '2025-08-07', releasedDate: '2025-08-02', receivedDate: '2025-08-17', closedDate: '2025-08-22', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g4-1', documentId: 'doc-g4-1', rev: 'B', initialProjectId: 'rv-755', openedDate: '2025-07-13', dueDate: '2025-08-27', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'wip' },
  { id: 'rev-g4-2', documentId: 'doc-g4-2', rev: 'C', initialProjectId: 'rv-755', openedDate: '2025-07-28', dueDate: '2025-09-16', releasedDate: '2025-09-07', receivedDate: '2025-09-22', closedDate: '2025-09-27', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-gd4-0', documentId: 'doc-gd4-0', rev: 'A', initialProjectId: 'rv-755', openedDate: '2025-07-08', dueDate: '2025-08-27', releasedDate: '2025-08-22', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g5-0', documentId: 'doc-g5-0', rev: 'A', initialProjectId: 'rv-777', openedDate: '2025-07-15', dueDate: '2025-08-24', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'wip' },
  { id: 'rev-g5-1', documentId: 'doc-g5-1', rev: 'B', initialProjectId: 'rv-777', openedDate: '2025-07-30', dueDate: '2025-09-13', releasedDate: '2025-09-06', receivedDate: '2025-09-21', closedDate: '2025-09-26', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g5-2', documentId: 'doc-g5-2', rev: 'C', initialProjectId: 'rv-777', openedDate: '2025-08-14', dueDate: '2025-10-03', releasedDate: '2025-09-24', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'in-review' },
  { id: 'rev-g5-3', documentId: 'doc-g5-3', rev: 'A', initialProjectId: 'rv-777', openedDate: '2025-08-29', dueDate: '2025-10-23', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'wip' },
  { id: 'rev-gd5-0', documentId: 'doc-gd5-0', rev: 'A', initialProjectId: 'rv-777', openedDate: '2025-07-25', dueDate: '2025-09-13', releasedDate: '2025-09-08', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'in-review' },
  { id: 'rev-gd5-1', documentId: 'doc-gd5-1', rev: 'B', initialProjectId: 'rv-777', openedDate: '2025-08-06', dueDate: '2025-09-25', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'wip' },
  { id: 'rev-g6-0', documentId: 'doc-g6-0', rev: 'A', initialProjectId: 'rv-469', openedDate: '2025-08-01', dueDate: '2025-09-10', releasedDate: '2025-09-05', receivedDate: '2025-09-20', closedDate: '2025-09-25', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g6-1', documentId: 'doc-g6-1', rev: 'B', initialProjectId: 'rv-469', openedDate: '2025-08-16', dueDate: '2025-09-30', releasedDate: '2025-09-23', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'in-review' },
  { id: 'rev-gd6-0', documentId: 'doc-gd6-0', rev: 'A', initialProjectId: 'rv-469', openedDate: '2025-08-11', dueDate: '2025-09-30', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'wip' },
  { id: 'rev-g7-0', documentId: 'doc-g7-0', rev: 'A', initialProjectId: 'rv-479', openedDate: '2025-08-18', dueDate: '2025-09-27', releasedDate: '2025-09-22', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'in-review' },
  { id: 'rev-g7-1', documentId: 'doc-g7-1', rev: 'B', initialProjectId: 'rv-479', openedDate: '2025-09-02', dueDate: '2025-10-17', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'wip' },
  { id: 'rev-g7-2', documentId: 'doc-g7-2', rev: 'C', initialProjectId: 'rv-479', openedDate: '2025-09-17', dueDate: '2025-11-06', releasedDate: '2025-10-28', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'signature' },
  { id: 'rev-gd7-0', documentId: 'doc-gd7-0', rev: 'A', initialProjectId: 'rv-479', openedDate: '2025-08-28', dueDate: '2025-10-17', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'signature' },
  { id: 'rev-gd7-1', documentId: 'doc-gd7-1', rev: 'B', initialProjectId: 'rv-479', openedDate: '2025-09-09', dueDate: '2025-10-29', releasedDate: '2025-10-24', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g8-0', documentId: 'doc-g8-0', rev: 'A', initialProjectId: 'rv-645', openedDate: '2025-09-04', dueDate: '2025-10-14', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'wip' },
  { id: 'rev-g8-1', documentId: 'doc-g8-1', rev: 'B', initialProjectId: 'rv-645', openedDate: '2025-09-19', dueDate: '2025-11-03', releasedDate: '2025-10-27', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'signature' },
  { id: 'rev-g8-2', documentId: 'doc-g8-2', rev: 'C', initialProjectId: 'rv-645', openedDate: '2025-10-04', dueDate: '2025-11-23', releasedDate: '2025-11-14', receivedDate: '2025-11-29', closedDate: '2025-12-04', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g8-3', documentId: 'doc-g8-3', rev: 'A', initialProjectId: 'rv-645', openedDate: '2025-10-19', dueDate: '2025-12-13', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'wip' },
  { id: 'rev-gd8-0', documentId: 'doc-gd8-0', rev: 'A', initialProjectId: 'rv-645', openedDate: '2025-09-14', dueDate: '2025-11-03', releasedDate: '2025-10-29', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g9-0', documentId: 'doc-g9-0', rev: 'A', initialProjectId: 'rv-779', openedDate: '2025-09-21', dueDate: '2025-10-31', releasedDate: '2025-10-26', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'signature' },
  { id: 'rev-g9-1', documentId: 'doc-g9-1', rev: 'B', initialProjectId: 'rv-779', openedDate: '2025-10-06', dueDate: '2025-11-20', releasedDate: '2025-11-13', receivedDate: '2025-11-28', closedDate: '2025-12-03', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-gd9-0', documentId: 'doc-gd9-0', rev: 'A', initialProjectId: 'rv-779', openedDate: '2025-10-01', dueDate: '2025-11-20', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'wip' },
  { id: 'rev-gd9-1', documentId: 'doc-gd9-1', rev: 'B', initialProjectId: 'rv-779', openedDate: '2025-10-13', dueDate: '2025-12-02', releasedDate: '2025-11-27', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g10-0', documentId: 'doc-g10-0', rev: 'A', initialProjectId: 'rv-780', openedDate: '2025-10-08', dueDate: '2025-11-17', releasedDate: '2025-11-12', receivedDate: '2025-11-27', closedDate: '2025-12-02', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g10-1', documentId: 'doc-g10-1', rev: 'B', initialProjectId: 'rv-780', openedDate: '2025-10-23', dueDate: '2025-12-07', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'wip' },
  { id: 'rev-g10-2', documentId: 'doc-g10-2', rev: 'C', initialProjectId: 'rv-780', openedDate: '2025-11-07', dueDate: '2025-12-27', releasedDate: '2025-12-18', receivedDate: '2026-01-02', closedDate: '2026-01-07', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-gd10-0', documentId: 'doc-gd10-0', rev: 'A', initialProjectId: 'rv-780', openedDate: '2025-10-18', dueDate: '2025-12-07', releasedDate: '2025-12-02', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g11-0', documentId: 'doc-g11-0', rev: 'A', initialProjectId: 'rv-781', openedDate: '2025-10-25', dueDate: '2025-12-04', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'wip' },
  { id: 'rev-g11-1', documentId: 'doc-g11-1', rev: 'B', initialProjectId: 'rv-781', openedDate: '2025-11-09', dueDate: '2025-12-24', releasedDate: '2025-12-17', receivedDate: '2026-01-01', closedDate: '2026-01-06', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g11-2', documentId: 'doc-g11-2', rev: 'C', initialProjectId: 'rv-781', openedDate: '2025-11-24', dueDate: '2026-01-13', releasedDate: '2026-01-04', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'in-review' },
  { id: 'rev-g11-3', documentId: 'doc-g11-3', rev: 'A', initialProjectId: 'rv-781', openedDate: '2025-12-09', dueDate: '2026-02-02', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'wip' },
  { id: 'rev-gd11-0', documentId: 'doc-gd11-0', rev: 'A', initialProjectId: 'rv-781', openedDate: '2025-11-04', dueDate: '2025-12-24', releasedDate: '2025-12-19', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'in-review' },
  { id: 'rev-gd11-1', documentId: 'doc-gd11-1', rev: 'B', initialProjectId: 'rv-781', openedDate: '2025-11-16', dueDate: '2026-01-05', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'wip' },
  { id: 'rev-g12-0', documentId: 'doc-g12-0', rev: 'A', initialProjectId: 'rv-782', openedDate: '2025-11-11', dueDate: '2025-12-21', releasedDate: '2025-12-16', receivedDate: '2025-12-31', closedDate: '2026-01-05', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g12-1', documentId: 'doc-g12-1', rev: 'B', initialProjectId: 'rv-782', openedDate: '2025-11-26', dueDate: '2026-01-10', releasedDate: '2026-01-03', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'in-review' },
  { id: 'rev-gd12-0', documentId: 'doc-gd12-0', rev: 'A', initialProjectId: 'rv-782', openedDate: '2025-11-21', dueDate: '2026-01-10', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'wip' },
  { id: 'rev-g13-0', documentId: 'doc-g13-0', rev: 'A', initialProjectId: 'rv-730', openedDate: '2025-11-28', dueDate: '2026-01-07', releasedDate: '2026-01-02', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'in-review' },
  { id: 'rev-g13-1', documentId: 'doc-g13-1', rev: 'B', initialProjectId: 'rv-730', openedDate: '2025-12-13', dueDate: '2026-01-27', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'wip' },
  { id: 'rev-g13-2', documentId: 'doc-g13-2', rev: 'C', initialProjectId: 'rv-730', openedDate: '2025-12-28', dueDate: '2026-02-16', releasedDate: '2026-02-07', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'signature' },
  { id: 'rev-gd13-0', documentId: 'doc-gd13-0', rev: 'A', initialProjectId: 'rv-730', openedDate: '2025-12-08', dueDate: '2026-01-27', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'signature' },
  { id: 'rev-gd13-1', documentId: 'doc-gd13-1', rev: 'B', initialProjectId: 'rv-730', openedDate: '2025-12-20', dueDate: '2026-02-08', releasedDate: '2026-02-03', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g14-0', documentId: 'doc-g14-0', rev: 'A', initialProjectId: 'rv-732', openedDate: '2025-12-15', dueDate: '2026-01-24', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'wip' },
  { id: 'rev-g14-1', documentId: 'doc-g14-1', rev: 'B', initialProjectId: 'rv-732', openedDate: '2025-12-30', dueDate: '2026-02-13', releasedDate: '2026-02-06', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'signature' },
  { id: 'rev-g14-2', documentId: 'doc-g14-2', rev: 'C', initialProjectId: 'rv-732', openedDate: '2026-01-14', dueDate: '2026-03-05', releasedDate: '2026-02-24', receivedDate: '2026-03-11', closedDate: '2026-03-16', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g14-3', documentId: 'doc-g14-3', rev: 'A', initialProjectId: 'rv-732', openedDate: '2026-01-29', dueDate: '2026-03-25', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'wip' },
  { id: 'rev-gd14-0', documentId: 'doc-gd14-0', rev: 'A', initialProjectId: 'rv-732', openedDate: '2025-12-25', dueDate: '2026-02-13', releasedDate: '2026-02-08', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g15-0', documentId: 'doc-g15-0', rev: 'A', initialProjectId: 'rv-766', openedDate: '2026-01-01', dueDate: '2026-02-10', releasedDate: '2026-02-05', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'signature' },
  { id: 'rev-g15-1', documentId: 'doc-g15-1', rev: 'B', initialProjectId: 'rv-766', openedDate: '2026-01-16', dueDate: '2026-03-02', releasedDate: '2026-02-23', receivedDate: '2026-03-10', closedDate: '2026-03-15', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-gd15-0', documentId: 'doc-gd15-0', rev: 'A', initialProjectId: 'rv-766', openedDate: '2026-01-11', dueDate: '2026-03-02', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'wip' },
  { id: 'rev-gd15-1', documentId: 'doc-gd15-1', rev: 'B', initialProjectId: 'rv-766', openedDate: '2026-01-23', dueDate: '2026-03-14', releasedDate: '2026-03-09', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g16-0', documentId: 'doc-g16-0', rev: 'A', initialProjectId: 'rv-768', openedDate: '2026-01-18', dueDate: '2026-02-27', releasedDate: '2026-02-22', receivedDate: '2026-03-09', closedDate: '2026-03-14', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g16-1', documentId: 'doc-g16-1', rev: 'B', initialProjectId: 'rv-768', openedDate: '2026-02-02', dueDate: '2026-03-19', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'wip' },
  { id: 'rev-g16-2', documentId: 'doc-g16-2', rev: 'C', initialProjectId: 'rv-768', openedDate: '2026-02-17', dueDate: '2026-04-08', releasedDate: '2026-03-30', receivedDate: '2026-04-14', closedDate: '2026-04-19', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-gd16-0', documentId: 'doc-gd16-0', rev: 'A', initialProjectId: 'rv-768', openedDate: '2026-01-28', dueDate: '2026-03-19', releasedDate: '2026-03-14', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g17-0', documentId: 'doc-g17-0', rev: 'A', initialProjectId: 'rv-746', openedDate: '2026-02-04', dueDate: '2026-03-16', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'wip' },
  { id: 'rev-g17-1', documentId: 'doc-g17-1', rev: 'B', initialProjectId: 'rv-746', openedDate: '2026-02-19', dueDate: '2026-04-05', releasedDate: '2026-03-29', receivedDate: '2026-04-13', closedDate: '2026-04-18', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g17-2', documentId: 'doc-g17-2', rev: 'C', initialProjectId: 'rv-746', openedDate: '2026-03-06', dueDate: '2026-04-25', releasedDate: '2026-04-16', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'in-review' },
  { id: 'rev-g17-3', documentId: 'doc-g17-3', rev: 'A', initialProjectId: 'rv-746', openedDate: '2026-03-21', dueDate: '2026-05-15', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'wip' },
  { id: 'rev-gd17-0', documentId: 'doc-gd17-0', rev: 'A', initialProjectId: 'rv-746', openedDate: '2026-02-14', dueDate: '2026-04-05', releasedDate: '2026-03-31', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'in-review' },
  { id: 'rev-gd17-1', documentId: 'doc-gd17-1', rev: 'B', initialProjectId: 'rv-746', openedDate: '2026-02-26', dueDate: '2026-04-17', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'wip' },
  { id: 'rev-g18-0', documentId: 'doc-g18-0', rev: 'A', initialProjectId: 'rv-747', openedDate: '2026-02-21', dueDate: '2026-04-02', releasedDate: '2026-03-28', receivedDate: '2026-04-12', closedDate: '2026-04-17', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g18-1', documentId: 'doc-g18-1', rev: 'B', initialProjectId: 'rv-747', openedDate: '2026-03-08', dueDate: '2026-04-22', releasedDate: '2026-04-15', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'in-review' },
  { id: 'rev-gd18-0', documentId: 'doc-gd18-0', rev: 'A', initialProjectId: 'rv-747', openedDate: '2026-03-03', dueDate: '2026-04-22', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'wip' },
  { id: 'rev-g19-0', documentId: 'doc-g19-0', rev: 'A', initialProjectId: 'rv-775', openedDate: '2026-03-10', dueDate: '2026-04-19', releasedDate: '2026-04-14', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'in-review' },
  { id: 'rev-g19-1', documentId: 'doc-g19-1', rev: 'B', initialProjectId: 'rv-775', openedDate: '2026-03-25', dueDate: '2026-05-09', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'wip' },
  { id: 'rev-g19-2', documentId: 'doc-g19-2', rev: 'C', initialProjectId: 'rv-775', openedDate: '2026-04-09', dueDate: '2026-05-29', releasedDate: '2026-05-20', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'signature' },
  { id: 'rev-gd19-0', documentId: 'doc-gd19-0', rev: 'A', initialProjectId: 'rv-775', openedDate: '2026-03-20', dueDate: '2026-05-09', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'signature' },
  { id: 'rev-gd19-1', documentId: 'doc-gd19-1', rev: 'B', initialProjectId: 'rv-775', openedDate: '2026-04-01', dueDate: '2026-05-21', releasedDate: '2026-05-16', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g20-0', documentId: 'doc-g20-0', rev: 'A', initialProjectId: 'rv-562', openedDate: '2026-03-27', dueDate: '2026-05-06', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'wip' },
  { id: 'rev-g20-1', documentId: 'doc-g20-1', rev: 'B', initialProjectId: 'rv-562', openedDate: '2026-04-11', dueDate: '2026-05-26', releasedDate: '2026-05-19', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'signature' },
  { id: 'rev-g20-2', documentId: 'doc-g20-2', rev: 'C', initialProjectId: 'rv-562', openedDate: '2026-04-26', dueDate: '2026-06-15', releasedDate: '2026-06-06', receivedDate: '2026-06-21', closedDate: '2026-06-26', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g20-3', documentId: 'doc-g20-3', rev: 'A', initialProjectId: 'rv-562', openedDate: '2026-05-11', dueDate: '2026-07-05', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Harris Bell', url: '', status: 'wip' },
  { id: 'rev-gd20-0', documentId: 'doc-gd20-0', rev: 'A', initialProjectId: 'rv-562', openedDate: '2026-04-06', dueDate: '2026-05-26', releasedDate: '2026-05-21', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g21-0', documentId: 'doc-g21-0', rev: 'A', initialProjectId: 'rv-570', openedDate: '2026-04-13', dueDate: '2026-05-23', releasedDate: '2026-05-18', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'signature' },
  { id: 'rev-g21-1', documentId: 'doc-g21-1', rev: 'B', initialProjectId: 'rv-570', openedDate: '2026-04-28', dueDate: '2026-06-12', releasedDate: '2026-06-05', receivedDate: '2026-06-20', closedDate: '2026-06-25', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-gd21-0', documentId: 'doc-gd21-0', rev: 'A', initialProjectId: 'rv-570', openedDate: '2026-04-23', dueDate: '2026-06-12', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Sofia Reyes', url: '', status: 'wip' },
  { id: 'rev-gd21-1', documentId: 'doc-gd21-1', rev: 'B', initialProjectId: 'rv-570', openedDate: '2026-05-05', dueDate: '2026-06-24', releasedDate: '2026-06-19', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g22-0', documentId: 'doc-g22-0', rev: 'A', initialProjectId: 'rv-561', openedDate: '2025-07-04', dueDate: '2025-08-13', releasedDate: '2025-08-08', receivedDate: '2025-08-23', closedDate: '2025-08-28', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g22-1', documentId: 'doc-g22-1', rev: 'B', initialProjectId: 'rv-561', openedDate: '2025-07-19', dueDate: '2025-09-02', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Lloyd Pedvis', url: '', status: 'wip' },
  { id: 'rev-g22-2', documentId: 'doc-g22-2', rev: 'C', initialProjectId: 'rv-561', openedDate: '2025-08-03', dueDate: '2025-09-22', releasedDate: '2025-09-13', receivedDate: '2025-09-28', closedDate: '2025-10-03', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-gd22-0', documentId: 'doc-gd22-0', rev: 'A', initialProjectId: 'rv-561', openedDate: '2025-07-14', dueDate: '2025-09-02', releasedDate: '2025-08-28', receivedDate: '', closedDate: '', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g23-0', documentId: 'doc-g23-0', rev: 'A', initialProjectId: 'rv-347', openedDate: '2025-07-21', dueDate: '2025-08-30', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'wip' },
  { id: 'rev-g23-1', documentId: 'doc-g23-1', rev: 'B', initialProjectId: 'rv-347', openedDate: '2025-08-05', dueDate: '2025-09-19', releasedDate: '2025-09-12', receivedDate: '2025-09-27', closedDate: '2025-10-02', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g23-2', documentId: 'doc-g23-2', rev: 'C', initialProjectId: 'rv-347', openedDate: '2025-08-20', dueDate: '2025-10-09', releasedDate: '2025-09-30', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'in-review' },
  { id: 'rev-g23-3', documentId: 'doc-g23-3', rev: 'A', initialProjectId: 'rv-347', openedDate: '2025-09-04', dueDate: '2025-10-29', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'wip' },
  { id: 'rev-gd23-0', documentId: 'doc-gd23-0', rev: 'A', initialProjectId: 'rv-347', openedDate: '2025-07-31', dueDate: '2025-09-19', releasedDate: '2025-09-14', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'in-review' },
  { id: 'rev-gd23-1', documentId: 'doc-gd23-1', rev: 'B', initialProjectId: 'rv-347', openedDate: '2025-08-12', dueDate: '2025-10-01', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Remi Rocheleau', url: '', status: 'wip' },
  { id: 'rev-g24-0', documentId: 'doc-g24-0', rev: 'A', initialProjectId: 'rv-569', openedDate: '2025-08-07', dueDate: '2025-09-16', releasedDate: '2025-09-11', receivedDate: '2025-09-26', closedDate: '2025-10-01', nextAction: '—', url: '', status: 'accepted' },
  { id: 'rev-g24-1', documentId: 'doc-g24-1', rev: 'B', initialProjectId: 'rv-569', openedDate: '2025-08-22', dueDate: '2025-10-06', releasedDate: '2025-09-29', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'in-review' },
  { id: 'rev-gd24-0', documentId: 'doc-gd24-0', rev: 'A', initialProjectId: 'rv-569', openedDate: '2025-08-17', dueDate: '2025-10-06', releasedDate: '', receivedDate: '', closedDate: '', nextAction: 'Kelly Osei', url: '', status: 'wip' },
]

/* Roughly two in three revisions have their file linked, which is how the data
   actually looks — a document is filed once it is released, and a rev that is
   still being written has nowhere to point yet. Deterministic (index-based, no
   randomness) so a reload never changes which rows carry a link. */
DOC_REVISIONS.forEach((r, i) => {
  if (i % 3 === 2) return
  const doc = DOCUMENTS.find((d) => d.id === r.documentId)
  if (!doc) return
  r.url = `https://files.elisen.example/${doc.kind === 'drawing' ? 'design-data' : 'deliverables'}/${doc.number.toLowerCase()}-rev-${r.rev.toLowerCase()}.pdf`
})

export const PROJECT_REVISION_LINKS: ProjectRevisionLink[] = DOC_REVISIONS.map((r) => ({
  id: `prl-${r.id}`,
  projectId: r.initialProjectId,
  revisionId: r.id,
}))

/**
 * Approvals, on the real `approval` shape. Aircraft and serials point at
 * Reference Data ids so the workspace's assign lists resolve to real records.
 *
 * `ap-galley` is the case study the client walked through on the call — a main
 * galley certified on two airframes, then extended to two more by a later
 * revision. It is built on the 767 pair because those exist in the client's own
 * aircraft catalogue; the call said 777, but inventing a model to match would
 * mean inventing reference data.
 */
export const APPROVALS: Approval[] = [
  {
    id: 'ap-galley', number: 'STC SA13-047',
    description: 'Main galley installation, forward cabin',
    primary: true, designApprovalHolder: 'Elisen Inc.',
    comment: 'Extended to two further airframes under revision 2. No design change, same galley configuration.',
    active: true,
    projectIds: [], aircraftIds: ['am-76733a', 'am-767300'],
    serialIds: ['sn-33423', 'sn-33424', 'sn-27135', 'sn-27136'],
  },
  {
    id: 'ap-1', number: 'STC SA24-018', description: 'Workstation console installation',
    primary: true, designApprovalHolder: 'Elisen Inc.', comment: '', active: true,
    projectIds: ['2'], aircraftIds: ['am-be350'], serialIds: ['sn-9033'],
  },
  {
    id: 'ap-2', number: 'STC SA26-102', description: 'Console map light addition',
    primary: false, designApprovalHolder: 'Elisen Inc.',
    comment: 'Change against STC SA24-018, not a standalone certificate.', active: true,
    projectIds: ['2'], aircraftIds: ['am-be350'], serialIds: [],
  },
  {
    id: 'ap-3', number: 'STC ST02981NY', description: 'iPad holder installation (FAA validation)',
    primary: true, designApprovalHolder: 'Elisen Inc.', comment: '', active: true,
    projectIds: ['5'], aircraftIds: ['am-737800'], serialIds: [],
  },
  {
    id: 'ap-g0', number: 'STC SA25-200', description: 'TCCA sSTC - Q400 Forward Cabin Reconfiguration',
    primary: true, designApprovalHolder: 'Elisen Inc.', comment: '', active: true,
    projectIds: ['rv-469'], aircraftIds: ['am-lear35a'], serialIds: ['sn-593'],
  },
  {
    id: 'ap-g1', number: 'STC SA25-203', description: 'Fireswift design upgrades',
    primary: true, designApprovalHolder: 'Elisen Inc.', comment: '', active: true,
    projectIds: ['rv-732'], aircraftIds: ['am-astra'], serialIds: ['sn-199'],
  },
  {
    id: 'ap-g2', number: 'STC SA25-206', description: 'Elisen - Quality System',
    primary: false, designApprovalHolder: 'Elisen Inc.',
    comment: 'Internal quality-system approval, carried against the parent DAO certificate.', active: true,
    projectIds: ['rv-561'], aircraftIds: [], serialIds: [],
  },
]

/**
 * Revisions. Every approval has at least revision 1: a certificate cannot exist
 * without having been issued once.
 */
export const APPROVAL_REVISIONS: ApprovalRevision[] = [
  {
    id: 'ar-galley-1', approvalId: 'ap-galley', revision: 1,
    changeDescription: 'Revision 1, main galley installed on the first two airframes (S/N 33423, 33424).',
    revisionDate: '2013-06-14', document: 'SA13-047-rev-1.pdf',
  },
  {
    id: 'ar-galley-2', approvalId: 'ap-galley', revision: 2,
    changeDescription: 'Two further airframes added to the approval (S/N 27135, 27136). Same galley configuration, no design change.',
    revisionDate: '2024-12-09', document: 'SA13-047-rev-2.pdf',
  },
  {
    id: 'ar-1-1', approvalId: 'ap-1', revision: 1,
    changeDescription: 'Revision 1, workstation console installed, LH forward position.',
    revisionDate: '2024-08-15', document: 'SA24-018-rev-1.pdf',
  },
  {
    id: 'ar-2-1', approvalId: 'ap-2', revision: 1,
    changeDescription: 'Revision 1, map light added to the console approved under STC SA24-018.',
    revisionDate: '2026-03-27', document: 'SA26-102-rev-1.pdf',
  },
  {
    id: 'ar-3-1', approvalId: 'ap-3', revision: 1,
    changeDescription: 'Revision 1: FAA validation of the Canadian iPad holder approval.',
    revisionDate: '2024-09-30', document: 'ST02981NY-rev-1.pdf',
  },
  {
    id: 'ar-g0-1', approvalId: 'ap-g0', revision: 1,
    changeDescription: 'Revision 1, forward cabin reconfiguration, 46-seat layout.',
    revisionDate: '2025-12-14', document: 'SA25-200-rev-1.pdf',
  },
  {
    id: 'ar-g0-2', approvalId: 'ap-g0', revision: 2,
    changeDescription: 'Galley monument relocated 12 inches aft to clear the reconfigured door surround.',
    revisionDate: '2026-05-21', document: 'SA25-200-rev-2.pdf',
  },
  {
    id: 'ar-g1-1', approvalId: 'ap-g1', revision: 1,
    changeDescription: 'Revision 1, fire-suppression and interior material upgrades.',
    revisionDate: '2026-04-29', document: 'SA25-203-rev-1.pdf',
  },
  {
    id: 'ar-g2-1', approvalId: 'ap-g2', revision: 1,
    changeDescription: 'Revision 1, quality system manual accepted.',
    revisionDate: '2025-11-16', document: 'SA25-206-rev-1.pdf',
  },
]
