import type { ProjectListRow } from '@/types/project'
import { REVIEW_ROWS } from './reviewFixtures'

/** Obviously-fake demo data for stories and the prototype shell. */
/**
 * Filter-coverage rows. Ten status/type/priority/active combinations crossed
 * with seven companies, cycling person responsible and budget health, so any
 * realistic two or three filter selections still return records instead of an
 * empty table. Comments mark them as demo data.
 */
export const COVERAGE_ROWS: ProjectListRow[] = [
  {
    id: 'gen-3300', number: '3300', subNumber: '00', type: 'internal',
    title: 'Cabin lighting upgrade',
    companyName: 'Abu Dhabi Aviation', companyNumber: '291',
    contactName: 'Yusuf Haddad', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 22.0, budgetHours: 40, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-01-01', dueDate: '2026-05-02', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '25000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3300', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3301', number: '3301', subNumber: '00', type: 'internal',
    title: 'Cargo liner replacement',
    companyName: 'Air Niugini', companyNumber: '287',
    contactName: 'Tahawar Durrani', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 75.2, budgetHours: 80, priority: '2-high', status: 'query', active: true,
    openedDate: '2026-02-02', dueDate: '2026-06-03', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '50000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3301', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3302', number: '3302', subNumber: '00', type: 'internal',
    title: 'Avionics rack revision',
    companyName: 'Duncan Aviation', companyNumber: '118',
    contactName: 'Priya Raman', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 148.8, budgetHours: 120, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-03-03', dueDate: '2026-07-04', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '75000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3302', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3303', number: '3303', subNumber: '00', type: 'internal',
    title: 'Seat track reinforcement',
    companyName: 'Top Aces', companyNumber: '204',
    contactName: 'Marc Lefebvre', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 0, budgetHours: 0, priority: '2-high', status: 'quoted', active: true,
    openedDate: '2026-04-04', dueDate: '2026-08-05', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '100000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3303', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3304', number: '3304', subNumber: '00', type: 'internal',
    title: 'Galley insert certification',
    companyName: 'CAE', companyNumber: '204',
    contactName: 'Annick Bergeron', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 176.0, budgetHours: 320, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-05-05', dueDate: '2026-09-06', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Internal design review scheduled.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3304', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3305', number: '3305', subNumber: '00', type: 'internal',
    title: 'Winglet aero assessment',
    companyName: 'Northwind Aerospace', companyNumber: '246',
    contactName: 'Nathalie Gagnon', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 37.6, budgetHours: 40, priority: '2-high', status: 'query', active: true,
    openedDate: '2026-06-06', dueDate: '2026-10-07', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '150000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Compliance matrix being updated.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3305', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3306', number: '3306', subNumber: '00', type: 'internal',
    title: 'Lavatory monument change',
    companyName: 'Elisen', companyNumber: '001',
    contactName: 'Sandra Okonkwo', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 99.2, budgetHours: 80, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-07-07', dueDate: '2026-11-08', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '175000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3306', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3307', number: '3307', subNumber: '00', type: 'external',
    title: 'Cockpit display retrofit',
    companyName: 'Abu Dhabi Aviation', companyNumber: '291',
    contactName: 'Yusuf Haddad', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 0, budgetHours: 0, priority: '1-fire', status: 'quoted', active: true,
    openedDate: '2026-08-08', dueDate: '2026-12-09', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '200000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3307', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3308', number: '3308', subNumber: '00', type: 'external',
    title: 'Fuel probe relocation',
    companyName: 'Air Niugini', companyNumber: '287',
    contactName: 'Tahawar Durrani', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 110.0, budgetHours: 200, priority: '1-fire', status: 'active', active: true,
    openedDate: '2026-09-09', dueDate: '2026-01-10', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '225000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3308', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3309', number: '3309', subNumber: '00', type: 'external',
    title: 'Antenna doubler design',
    companyName: 'Duncan Aviation', companyNumber: '118',
    contactName: 'Priya Raman', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 300.8, budgetHours: 320, priority: '1-fire', status: 'query', active: true,
    openedDate: '2026-01-10', dueDate: '2026-02-11', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '25000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3309', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3310', number: '3310', subNumber: '00', type: 'external',
    title: 'Cabin lighting upgrade',
    companyName: 'Top Aces', companyNumber: '204',
    contactName: 'Marc Lefebvre', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 49.6, budgetHours: 40, priority: '1-fire', status: 'active', active: true,
    openedDate: '2026-02-11', dueDate: '2026-03-12', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '50000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Internal design review scheduled.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3310', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3311', number: '3311', subNumber: '00', type: 'external',
    title: 'Cargo liner replacement',
    companyName: 'CAE', companyNumber: '204',
    contactName: 'Annick Bergeron', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 0, budgetHours: 0, priority: '1-fire', status: 'quoted', active: true,
    openedDate: '2026-03-12', dueDate: '2026-04-13', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '75000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Compliance matrix being updated.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3311', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3312', number: '3312', subNumber: '00', type: 'external',
    title: 'Avionics rack revision',
    companyName: 'Northwind Aerospace', companyNumber: '246',
    contactName: 'Nathalie Gagnon', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 66.0, budgetHours: 120, priority: '1-fire', status: 'active', active: true,
    openedDate: '2026-04-13', dueDate: '2026-05-14', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '100000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3312', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3313', number: '3313', subNumber: '00', type: 'external',
    title: 'Seat track reinforcement',
    companyName: 'Elisen', companyNumber: '001',
    contactName: 'Piotr Nowak', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 188.0, budgetHours: 200, priority: '1-fire', status: 'query', active: true,
    openedDate: '2026-05-14', dueDate: '2026-06-15', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3313', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3314', number: '3314', subNumber: '00', type: 'preferred-duncan',
    title: 'Galley insert certification',
    companyName: 'Abu Dhabi Aviation', companyNumber: '291',
    contactName: 'Yusuf Haddad', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 396.8, budgetHours: 320, priority: '3-med', status: 'active', active: true,
    openedDate: '2026-06-15', dueDate: '2026-07-16', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '150000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3314', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3315', number: '3315', subNumber: '00', type: 'preferred-duncan',
    title: 'Winglet aero assessment',
    companyName: 'Air Niugini', companyNumber: '287',
    contactName: 'Tahawar Durrani', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 0, budgetHours: 0, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2026-07-16', dueDate: '2026-08-17', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '175000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3315', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3316', number: '3316', subNumber: '00', type: 'preferred-duncan',
    title: 'Lavatory monument change',
    companyName: 'Duncan Aviation', companyNumber: '118',
    contactName: 'Priya Raman', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 44.0, budgetHours: 80, priority: '3-med', status: 'active', active: true,
    openedDate: '2026-08-17', dueDate: '2026-09-18', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '200000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Internal design review scheduled.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3316', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3317', number: '3317', subNumber: '00', type: 'preferred-duncan',
    title: 'Cockpit display retrofit',
    companyName: 'Top Aces', companyNumber: '204',
    contactName: 'Marc Lefebvre', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 112.8, budgetHours: 120, priority: '3-med', status: 'query', active: true,
    openedDate: '2026-09-18', dueDate: '2026-10-19', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '225000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Compliance matrix being updated.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3317', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3318', number: '3318', subNumber: '00', type: 'preferred-duncan',
    title: 'Fuel probe relocation',
    companyName: 'CAE', companyNumber: '204',
    contactName: 'Annick Bergeron', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 248.0, budgetHours: 200, priority: '3-med', status: 'active', active: true,
    openedDate: '2026-01-19', dueDate: '2026-11-20', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '25000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3318', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3319', number: '3319', subNumber: '00', type: 'preferred-duncan',
    title: 'Antenna doubler design',
    companyName: 'Northwind Aerospace', companyNumber: '246',
    contactName: 'Nathalie Gagnon', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 0, budgetHours: 0, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2026-02-20', dueDate: '2026-12-21', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '50000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3319', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3320', number: '3320', subNumber: '00', type: 'preferred-duncan',
    title: 'Cabin lighting upgrade',
    companyName: 'Elisen', companyNumber: '001',
    contactName: '', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 22.0, budgetHours: 40, priority: '3-med', status: 'active', active: true,
    openedDate: '2026-03-21', dueDate: '2026-01-22', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '75000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3320', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3321', number: '3321', subNumber: '00', type: 'preferred-topaces',
    title: 'Cargo liner replacement',
    companyName: 'Abu Dhabi Aviation', companyNumber: '291',
    contactName: 'Yusuf Haddad', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 75.2, budgetHours: 80, priority: '2-high', status: 'query', active: true,
    openedDate: '2026-04-22', dueDate: '2026-02-23', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '100000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3321', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3322', number: '3322', subNumber: '00', type: 'preferred-topaces',
    title: 'Avionics rack revision',
    companyName: 'Air Niugini', companyNumber: '287',
    contactName: 'Tahawar Durrani', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 148.8, budgetHours: 120, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-05-23', dueDate: '2026-03-24', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Internal design review scheduled.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3322', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3323', number: '3323', subNumber: '00', type: 'preferred-topaces',
    title: 'Seat track reinforcement',
    companyName: 'Duncan Aviation', companyNumber: '118',
    contactName: 'Priya Raman', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 0, budgetHours: 0, priority: '2-high', status: 'quoted', active: true,
    openedDate: '2026-06-24', dueDate: '2026-04-25', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '150000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Compliance matrix being updated.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3323', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3324', number: '3324', subNumber: '00', type: 'preferred-topaces',
    title: 'Galley insert certification',
    companyName: 'Top Aces', companyNumber: '204',
    contactName: 'Marc Lefebvre', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 176.0, budgetHours: 320, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-07-25', dueDate: '2026-05-26', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '175000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3324', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3325', number: '3325', subNumber: '00', type: 'preferred-topaces',
    title: 'Winglet aero assessment',
    companyName: 'CAE', companyNumber: '204',
    contactName: 'Annick Bergeron', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 37.6, budgetHours: 40, priority: '2-high', status: 'query', active: true,
    openedDate: '2026-08-26', dueDate: '2026-06-27', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '200000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3325', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3326', number: '3326', subNumber: '00', type: 'preferred-topaces',
    title: 'Lavatory monument change',
    companyName: 'Northwind Aerospace', companyNumber: '246',
    contactName: 'Nathalie Gagnon', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 99.2, budgetHours: 80, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-09-27', dueDate: '2026-07-02', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '225000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3326', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3327', number: '3327', subNumber: '00', type: 'preferred-topaces',
    title: 'Cockpit display retrofit',
    companyName: 'Elisen', companyNumber: '001',
    contactName: 'Tomás Herrera', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 0, budgetHours: 0, priority: '2-high', status: 'quoted', active: true,
    openedDate: '2026-01-01', dueDate: '2026-08-03', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '25000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3327', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3328', number: '3328', subNumber: '00', type: 'external',
    title: 'Fuel probe relocation',
    companyName: 'Abu Dhabi Aviation', companyNumber: '291',
    contactName: 'Yusuf Haddad', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 110.0, budgetHours: 200, priority: '4-low', status: 'active', active: true,
    openedDate: '2026-02-02', dueDate: '2026-09-04', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '50000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Internal design review scheduled.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3328', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3329', number: '3329', subNumber: '00', type: 'external',
    title: 'Antenna doubler design',
    companyName: 'Air Niugini', companyNumber: '287',
    contactName: 'Tahawar Durrani', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 300.8, budgetHours: 320, priority: '4-low', status: 'complete', active: true,
    openedDate: '2026-03-03', dueDate: '2026-10-05', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '75000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Compliance matrix being updated.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3329', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3330', number: '3330', subNumber: '00', type: 'external',
    title: 'Cabin lighting upgrade',
    companyName: 'Duncan Aviation', companyNumber: '118',
    contactName: 'Priya Raman', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 49.6, budgetHours: 40, priority: '4-low', status: 'on-hold', active: true,
    openedDate: '2026-04-04', dueDate: '2026-11-06', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '100000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3330', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3331', number: '3331', subNumber: '00', type: 'external',
    title: 'Cargo liner replacement',
    companyName: 'Top Aces', companyNumber: '204',
    contactName: 'Marc Lefebvre', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 0, budgetHours: 0, priority: '4-low', status: 'query', active: true,
    openedDate: '2026-05-05', dueDate: '2026-12-07', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3331', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3332', number: '3332', subNumber: '00', type: 'external',
    title: 'Avionics rack revision',
    companyName: 'CAE', companyNumber: '204',
    contactName: 'Annick Bergeron', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 66.0, budgetHours: 120, priority: '4-low', status: 'quoted', active: true,
    openedDate: '2026-06-06', dueDate: '2026-01-08', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '150000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3332', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3333', number: '3333', subNumber: '00', type: 'external',
    title: 'Seat track reinforcement',
    companyName: 'Northwind Aerospace', companyNumber: '246',
    contactName: 'Nathalie Gagnon', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 188.0, budgetHours: 200, priority: '4-low', status: 'tentative', active: true,
    openedDate: '2026-07-07', dueDate: '2026-02-09', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '175000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3333', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3334', number: '3334', subNumber: '00', type: 'external',
    title: 'Galley insert certification',
    companyName: 'Elisen', companyNumber: '001',
    contactName: 'Fiona Blackwood', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 396.8, budgetHours: 320, priority: '4-low', status: 'active', active: true,
    openedDate: '2026-08-08', dueDate: '2026-03-10', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '200000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Internal design review scheduled.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3334', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3335', number: '3335', subNumber: '00', type: 'preferred',
    title: 'Winglet aero assessment',
    companyName: 'Abu Dhabi Aviation', companyNumber: '291',
    contactName: 'Yusuf Haddad', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 0, budgetHours: 0, priority: '5-lowest', status: 'complete', active: true,
    openedDate: '2026-09-09', dueDate: '2026-04-11', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '225000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Compliance matrix being updated.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3335', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3336', number: '3336', subNumber: '00', type: 'preferred',
    title: 'Lavatory monument change',
    companyName: 'Air Niugini', companyNumber: '287',
    contactName: 'Tahawar Durrani', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 44.0, budgetHours: 80, priority: '5-lowest', status: 'on-hold', active: true,
    openedDate: '2026-01-10', dueDate: '2026-05-12', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '25000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3336', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3337', number: '3337', subNumber: '00', type: 'preferred',
    title: 'Cockpit display retrofit',
    companyName: 'Duncan Aviation', companyNumber: '118',
    contactName: 'Priya Raman', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 112.8, budgetHours: 120, priority: '5-lowest', status: 'query', active: true,
    openedDate: '2026-02-11', dueDate: '2026-06-13', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '50000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3337', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3338', number: '3338', subNumber: '00', type: 'preferred',
    title: 'Fuel probe relocation',
    companyName: 'Top Aces', companyNumber: '204',
    contactName: 'Marc Lefebvre', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 248.0, budgetHours: 200, priority: '5-lowest', status: 'quoted', active: true,
    openedDate: '2026-03-12', dueDate: '2026-07-14', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '75000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3338', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3339', number: '3339', subNumber: '00', type: 'preferred',
    title: 'Antenna doubler design',
    companyName: 'CAE', companyNumber: '204',
    contactName: 'Annick Bergeron', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 0, budgetHours: 0, priority: '5-lowest', status: 'tentative', active: true,
    openedDate: '2026-04-13', dueDate: '2026-08-15', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '100000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3339', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3340', number: '3340', subNumber: '00', type: 'preferred',
    title: 'Cabin lighting upgrade',
    companyName: 'Northwind Aerospace', companyNumber: '246',
    contactName: 'Nathalie Gagnon', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 22.0, budgetHours: 40, priority: '5-lowest', status: 'active', active: true,
    openedDate: '2026-05-14', dueDate: '2026-09-16', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Internal design review scheduled.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3340', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3341', number: '3341', subNumber: '00', type: 'preferred',
    title: 'Cargo liner replacement',
    companyName: 'Elisen', companyNumber: '001',
    contactName: 'Nadia Rahman', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 75.2, budgetHours: 80, priority: '5-lowest', status: 'complete', active: true,
    openedDate: '2026-06-15', dueDate: '2026-10-17', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '150000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Compliance matrix being updated.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3341', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3342', number: '3342', subNumber: '00', type: 'other',
    title: 'Avionics rack revision',
    companyName: 'Abu Dhabi Aviation', companyNumber: '291',
    contactName: 'Yusuf Haddad', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 120, budgetHours: 120, priority: '3-med', status: 'on-hold', active: false,
    openedDate: '2026-07-16', dueDate: '2026-11-18', aircraftInputDate: '', closedDate: '2026-11-30',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '175000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3342', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3343', number: '3343', subNumber: '00', type: 'other',
    title: 'Seat track reinforcement',
    companyName: 'Air Niugini', companyNumber: '287',
    contactName: 'Tahawar Durrani', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 0, budgetHours: 0, priority: '3-med', status: 'query', active: false,
    openedDate: '2026-08-17', dueDate: '2026-12-19', aircraftInputDate: '', closedDate: '2026-11-30',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '200000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3343', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3344', number: '3344', subNumber: '00', type: 'other',
    title: 'Galley insert certification',
    companyName: 'Duncan Aviation', companyNumber: '118',
    contactName: 'Priya Raman', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 320, budgetHours: 320, priority: '3-med', status: 'quoted', active: false,
    openedDate: '2026-09-18', dueDate: '2026-01-20', aircraftInputDate: '', closedDate: '2026-11-30',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '225000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3344', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3345', number: '3345', subNumber: '00', type: 'other',
    title: 'Winglet aero assessment',
    companyName: 'Top Aces', companyNumber: '204',
    contactName: 'Marc Lefebvre', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 40, budgetHours: 40, priority: '3-med', status: 'tentative', active: false,
    openedDate: '2026-01-19', dueDate: '2026-02-21', aircraftInputDate: '', closedDate: '2026-11-30',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '25000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3345', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3346', number: '3346', subNumber: '00', type: 'other',
    title: 'Lavatory monument change',
    companyName: 'CAE', companyNumber: '204',
    contactName: 'Annick Bergeron', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 80, budgetHours: 80, priority: '3-med', status: 'active', active: false,
    openedDate: '2026-02-20', dueDate: '2026-03-22', aircraftInputDate: '', closedDate: '2026-11-30',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '50000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Internal design review scheduled.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3346', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3347', number: '3347', subNumber: '00', type: 'other',
    title: 'Cockpit display retrofit',
    companyName: 'Northwind Aerospace', companyNumber: '246',
    contactName: 'Nathalie Gagnon', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 0, budgetHours: 0, priority: '3-med', status: 'complete', active: false,
    openedDate: '2026-03-21', dueDate: '2026-04-23', aircraftInputDate: '', closedDate: '2026-11-30',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '75000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Compliance matrix being updated.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3347', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3348', number: '3348', subNumber: '00', type: 'other',
    title: 'Fuel probe relocation',
    companyName: 'Elisen', companyNumber: '001',
    contactName: 'Ewan Sinclair', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 200, budgetHours: 200, priority: '3-med', status: 'on-hold', active: false,
    openedDate: '2026-04-22', dueDate: '2026-05-24', aircraftInputDate: '', closedDate: '2026-11-30',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '100000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3348', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3349', number: '3349', subNumber: '00', type: 'external',
    title: 'Antenna doubler design',
    companyName: 'Abu Dhabi Aviation', companyNumber: '291',
    contactName: 'Yusuf Haddad', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 300.8, budgetHours: 320, priority: '5-lowest', status: 'query', active: true,
    openedDate: '2026-05-23', dueDate: '2026-06-25', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3349', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3350', number: '3350', subNumber: '00', type: 'external',
    title: 'Cabin lighting upgrade',
    companyName: 'Air Niugini', companyNumber: '287',
    contactName: 'Tahawar Durrani', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 49.6, budgetHours: 40, priority: '5-lowest', status: 'quoted', active: true,
    openedDate: '2026-06-24', dueDate: '2026-07-26', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '150000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3350', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3351', number: '3351', subNumber: '00', type: 'external',
    title: 'Cargo liner replacement',
    companyName: 'Duncan Aviation', companyNumber: '118',
    contactName: 'Priya Raman', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 0, budgetHours: 0, priority: '5-lowest', status: 'tentative', active: true,
    openedDate: '2026-07-25', dueDate: '2026-08-27', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '175000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3351', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3352', number: '3352', subNumber: '00', type: 'external',
    title: 'Avionics rack revision',
    companyName: 'Top Aces', companyNumber: '204',
    contactName: 'Marc Lefebvre', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 66.0, budgetHours: 120, priority: '5-lowest', status: 'active', active: true,
    openedDate: '2026-08-26', dueDate: '2026-09-02', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '200000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Internal design review scheduled.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3352', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3353', number: '3353', subNumber: '00', type: 'external',
    title: 'Seat track reinforcement',
    companyName: 'CAE', companyNumber: '204',
    contactName: 'Annick Bergeron', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 188.0, budgetHours: 200, priority: '5-lowest', status: 'complete', active: true,
    openedDate: '2026-09-27', dueDate: '2026-10-03', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '225000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Compliance matrix being updated.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3353', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3354', number: '3354', subNumber: '00', type: 'external',
    title: 'Galley insert certification',
    companyName: 'Northwind Aerospace', companyNumber: '246',
    contactName: 'Nathalie Gagnon', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 396.8, budgetHours: 320, priority: '5-lowest', status: 'on-hold', active: true,
    openedDate: '2026-01-01', dueDate: '2026-11-04', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '25000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3354', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3355', number: '3355', subNumber: '00', type: 'external',
    title: 'Winglet aero assessment',
    companyName: 'Elisen', companyNumber: '001',
    contactName: 'Camille Rousseau', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 0, budgetHours: 0, priority: '5-lowest', status: 'query', active: true,
    openedDate: '2026-02-02', dueDate: '2026-12-05', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '50000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3355', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3356', number: '3356', subNumber: '00', type: 'internal',
    title: 'Lavatory monument change',
    companyName: 'Abu Dhabi Aviation', companyNumber: '291',
    contactName: 'Yusuf Haddad', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 44.0, budgetHours: 80, priority: '1-fire', status: 'quoted', active: true,
    openedDate: '2026-03-03', dueDate: '2026-01-06', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '75000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3356', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3357', number: '3357', subNumber: '00', type: 'internal',
    title: 'Cockpit display retrofit',
    companyName: 'Air Niugini', companyNumber: '287',
    contactName: 'Tahawar Durrani', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 112.8, budgetHours: 120, priority: '1-fire', status: 'tentative', active: true,
    openedDate: '2026-04-04', dueDate: '2026-02-07', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '100000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3357', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3358', number: '3358', subNumber: '00', type: 'internal',
    title: 'Fuel probe relocation',
    companyName: 'Duncan Aviation', companyNumber: '118',
    contactName: 'Priya Raman', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 248.0, budgetHours: 200, priority: '1-fire', status: 'active', active: true,
    openedDate: '2026-05-05', dueDate: '2026-03-08', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Internal design review scheduled.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3358', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3359', number: '3359', subNumber: '00', type: 'internal',
    title: 'Antenna doubler design',
    companyName: 'Top Aces', companyNumber: '204',
    contactName: 'Marc Lefebvre', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 0, budgetHours: 0, priority: '1-fire', status: 'complete', active: true,
    openedDate: '2026-06-06', dueDate: '2026-04-09', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '150000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Compliance matrix being updated.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3359', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3360', number: '3360', subNumber: '00', type: 'internal',
    title: 'Cabin lighting upgrade',
    companyName: 'CAE', companyNumber: '204',
    contactName: 'Annick Bergeron', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 22.0, budgetHours: 40, priority: '1-fire', status: 'on-hold', active: true,
    openedDate: '2026-07-07', dueDate: '2026-05-10', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '175000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3360', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3361', number: '3361', subNumber: '00', type: 'internal',
    title: 'Cargo liner replacement',
    companyName: 'Northwind Aerospace', companyNumber: '246',
    contactName: 'Nathalie Gagnon', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 75.2, budgetHours: 80, priority: '1-fire', status: 'query', active: true,
    openedDate: '2026-08-08', dueDate: '2026-06-11', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '200000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3361', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3362', number: '3362', subNumber: '00', type: 'internal',
    title: 'Avionics rack revision',
    companyName: 'Elisen', companyNumber: '001',
    contactName: 'Dev Patel', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 148.8, budgetHours: 120, priority: '1-fire', status: 'quoted', active: true,
    openedDate: '2026-09-09', dueDate: '2026-07-12', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '225000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'yes', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3362', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3363', number: '3363', subNumber: '00', type: 'preferred',
    title: 'Seat track reinforcement',
    companyName: 'Abu Dhabi Aviation', companyNumber: '291',
    contactName: 'Yusuf Haddad', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 0, budgetHours: 0, priority: '4-low', status: 'tentative', active: false,
    openedDate: '2026-01-10', dueDate: '2026-08-13', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '25000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3363', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3364', number: '3364', subNumber: '00', type: 'preferred',
    title: 'Galley insert certification',
    companyName: 'Air Niugini', companyNumber: '287',
    contactName: 'Tahawar Durrani', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 176.0, budgetHours: 320, priority: '4-low', status: 'active', active: false,
    openedDate: '2026-02-11', dueDate: '2026-09-14', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '50000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Internal design review scheduled.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3364', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
  {
    id: 'gen-3365', number: '3365', subNumber: '00', type: 'preferred',
    title: 'Winglet aero assessment',
    companyName: 'Duncan Aviation', companyNumber: '118',
    contactName: 'Priya Raman', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 37.6, budgetHours: 40, priority: '4-low', status: 'complete', active: false,
    openedDate: '2026-03-12', dueDate: '2026-10-15', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '75000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Compliance matrix being updated.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3365', aircraftId: 'am-be350', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'gen-3366', number: '3366', subNumber: '00', type: 'preferred',
    title: 'Lavatory monument change',
    companyName: 'Top Aces', companyNumber: '204',
    contactName: 'Marc Lefebvre', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 99.2, budgetHours: 80, priority: '4-low', status: 'on-hold', active: false,
    openedDate: '2026-04-13', dueDate: '2026-11-16', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '100000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Awaiting customer purchase order.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3366', aircraftId: 'am-lear35a', modelName: 'Learjet 35A', modelNumber: 'Lear 35A', manufacturer: 'Bombardier Learjet' }],
  },
  {
    id: 'gen-3367', number: '3367', subNumber: '00', type: 'preferred',
    title: 'Cockpit display retrofit',
    companyName: 'CAE', companyNumber: '204',
    contactName: 'Annick Bergeron', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 0, budgetHours: 0, priority: '4-low', status: 'query', active: false,
    openedDate: '2026-05-14', dueDate: '2026-12-17', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Draft stress report under review.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3367', aircraftId: 'am-767300', modelName: 'Boeing 767 Series', modelNumber: '767-300', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3368', number: '3368', subNumber: '00', type: 'preferred',
    title: 'Fuel probe relocation',
    companyName: 'Northwind Aerospace', companyNumber: '246',
    contactName: 'Nathalie Gagnon', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 110.0, budgetHours: 200, priority: '4-low', status: 'quoted', active: false,
    openedDate: '2026-06-15', dueDate: '2026-01-18', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '150000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'TCCA submission being prepared.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3368', aircraftId: 'am-737800', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: 'gen-3369', number: '3369', subNumber: '00', type: 'preferred',
    title: 'Antenna doubler design',
    companyName: 'Elisen', companyNumber: '001',
    contactName: 'Chantal Boisvert', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 300.8, budgetHours: 320, priority: '4-low', status: 'tentative', active: false,
    openedDate: '2026-07-16', dueDate: '2026-02-19', aircraftInputDate: '', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '175000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Waiting on vendor drawings.',
    comments: 'Demo coverage row so filter combinations return results.',
    aircraft: [{ id: 'ac-gen-3369', aircraftId: 'am-astra', modelName: 'Astra SPX', modelNumber: 'Astra SPX', manufacturer: 'Gulfstream' }],
  },
]

export const PROJECT_ROWS: ProjectListRow[] = [
  {
    id: '1', number: '3200', subNumber: '00', type: 'internal',
    title: 'STC: Cabin Interior Modification, Cert Program',
    companyName: 'Northwind Aerospace', companyNumber: '246',
    contactName: 'Nathalie Gagnon', contactEmail: 'nathalie.gagnon@northwindaerospace.example',
    personResponsible: 'Sofia Reyes',
    actualHours: 44, budgetHours: 80, priority: '1-fire', status: 'quoted', active: true,
    openedDate: '2026-01-01', dueDate: '2026-07-04', aircraftInputDate: '2026-04-16', closedDate: '',
    scope: ['design', 'validation', 'certification', 'parts-kit'],
    contractCurrency: 'USD', contractValue: '485000',
    proposalSubmitted: 'no', proposalSubmittedDate: '2026-07-04', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Follow up with client on outstanding documentation.',
    comments: 'Certification project covering design substantiation, compliance documentation and TCCA approval.',
    aircraft: [{ id: 'ac-1', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: '2', number: '3201', subNumber: '00', type: 'preferred-duncan',
    title: 'Console Map Light Addition',
    companyName: 'Duncan Aviation', companyNumber: '118',
    contactName: 'Priya Raman', contactEmail: 'priya.raman@duncanaviation.example',
    personResponsible: 'Lloyd Pedvis',
    actualHours: 312, budgetHours: 280, priority: '2-high', status: 'active', active: true,
    openedDate: '2025-11-12', dueDate: '2026-03-27', aircraftInputDate: '2025-12-05', closedDate: '',
    scope: ['design', 'certification'],
    contractCurrency: 'USD', contractValue: '96000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-11-05', proposalAccepted: 'yes', proposalAcceptedDate: '2025-11-10',
    nextAction: 'Awaiting final sign-off from Duncan on the revised drawing.',
    comments: 'Change to the previously approved console STC, adding map lights.',
    aircraft: [{ id: 'ac-2', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: '3', number: '3202', subNumber: '01', type: 'preferred-topaces',
    title: 'Wiring Provisions: Underfloor Harness',
    companyName: 'Top Aces', companyNumber: '092',
    contactName: 'Marc Lefebvre', contactEmail: 'marc.lefebvre@topaces.example',
    personResponsible: 'Sofia Reyes',
    actualHours: 128, budgetHours: 400, priority: '3-med', status: 'active', active: true,
    openedDate: '2026-02-01', dueDate: '2026-09-15', aircraftInputDate: '', closedDate: '',
    scope: ['design', 'validation'],
    contractCurrency: 'USD', contractValue: '210000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2026-01-20', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Harness routing review with Top Aces engineering next week.', comments: 'Underfloor wiring provisions for a future mission-system installation.',
    aircraft: [{ id: 'ac-4', modelName: 'A-4N Skyhawk', modelNumber: 'A-4N', manufacturer: 'Douglas' }],
  },
  {
    id: '4', number: '3203', subNumber: '00', type: 'external',
    title: 'Galley Modification: Weight & Balance',
    companyName: 'Abu Dhabi Aviation', companyNumber: '401',
    contactName: 'Yusuf Haddad', contactEmail: 'yusuf.haddad@abudhabiaviation.example',
    personResponsible: 'Remi Rocheleau',
    actualHours: 0, budgetHours: 160, priority: '4-low', status: 'quoted', active: true,
    openedDate: '2026-07-01', dueDate: '2026-10-30', aircraftInputDate: '', closedDate: '',
    scope: ['design'],
    contractCurrency: 'USD', contractValue: '68000', proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Quote issued, awaiting customer decision.', comments: 'Galley relocation with updated weight and balance substantiation.',
    aircraft: [{ id: 'ac-5', modelName: 'Dash 8-400', modelNumber: 'DHC-8-402', manufacturer: 'De Havilland' }],
  },
  {
    id: '5', number: '3204', subNumber: '00', type: 'external',
    title: 'iPad Holder Installation: Cockpit',
    companyName: 'Meridian Charter', companyNumber: '377',
    contactName: 'Jane Doe', contactEmail: 'jane.doe@meridiancharter.example',
    personResponsible: 'Kelly Osei',
    actualHours: 96, budgetHours: 96, priority: '3-med', status: 'complete', active: true,
    openedDate: '2024-03-04', dueDate: '2024-05-01', aircraftInputDate: '2024-03-10', closedDate: '2024-05-01',
    scope: ['design', 'validation', 'certification'],
    contractCurrency: 'USD', contractValue: '42000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2024-02-15', proposalAccepted: 'yes', proposalAcceptedDate: '2024-02-20',
    nextAction: 'None, project closed.', comments: 'Closed out, certificate issued.',
    aircraft: [{ id: 'ac-3', modelName: 'B737-800', modelNumber: '737-8', manufacturer: 'Boeing' }],
  },
  {
    id: '6', number: '3205', subNumber: '02', type: 'internal',
    title: 'DAO Activities: Process & Procedure Update',
    companyName: 'Elisen', companyNumber: '001',
    contactName: 'Denis Fortier', contactEmail: '',
    personResponsible: 'Harris Bell',
    actualHours: 58, budgetHours: 40, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-01-15', dueDate: '2026-11-30', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'USD', contractValue: '125000', proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Procedure revision out for internal review.', comments: 'Internal DAO cost centre, no customer.',
    aircraft: [{ id: 'ac-6', modelName: 'Not aircraft-specific', modelNumber: 'N/A', manufacturer: 'Elisen' }],
  },
  // The client's real Projects Review data — same entity, one store.
  ...REVIEW_ROWS,
  ...COVERAGE_ROWS,
]

// COMPANIES/CONTACTS moved to the Lookup Tables store (lib/lookupFixtures.ts).
export const PEOPLE = ['Sofia Reyes', 'Lloyd Pedvis', 'Remi Rocheleau', 'Kelly Osei', 'Harris Bell']

/** Numbers already used — drives the duplicate-number validation. */
export const TAKEN_NUMBERS = Array.from(new Set(PROJECT_ROWS.map((r) => r.number)))
export const NEXT_AVAILABLE_NUMBER = '3206'

/** Next unused 4-digit project number, given the current row set. */
export function getNextProjectNumber(rows: ProjectListRow[]): string {
  const max = rows.reduce((m, r) => Math.max(m, Number(r.number) || 0), Number(NEXT_AVAILABLE_NUMBER) - 1)
  return String(max + 1)
}
