import type { ProjectListRow } from '@/types/project'

/**
 * The client's real Projects Review data, transcribed from their legacy
 * screens (Priorities / Top Aces / Duncan / External / Internal /
 * Outstanding RFQs / Completed RFQs). Those 7 tabs were one `project`
 * table filtered 7 ways — see docs/DECISIONS.md — so this is one flat
 * list, with `status` and `type` carrying what the tab membership used
 * to encode:
 *   status 'query'   = Outstanding RFQ      status 'quoted' = Completed RFQ
 *   status 'active'  = the four type tabs   type            = which type tab
 * `openedDate` on the RFQ rows is back-calculated from the Aging value
 * shown on the legacy screen, so Aging still reads correctly today.
 *
 * Budget/actual hours, contacts, company numbers and person-responsible are
 * **demo values**, not transcribed from the client — the legacy Review
 * screens didn't carry them, and leaving them blank made the health columns
 * unreadable. Budgets scale with priority; actuals are only set on
 * in-progress rows (RFQs legitimately have nothing booked before award) and
 * are spread to give a realistic on-track / near-budget / over-budget mix.
 * Replace wholesale once real figures arrive.
 */
export const REVIEW_ROWS: ProjectListRow[] = [
  {
    id: 'rv-764', number: '3179', subNumber: '07', type: 'external',
    title: 'Pilatus - Additional provisions and console modifications',
    companyName: 'Cert Center Canada (3C)', companyNumber: '167', contactName: 'Julie Lamontagne', contactEmail: 'julie.lamontagne@certcentercanadac.example', personResponsible: 'Sofia Reyes',
    actualHours: 0.0, budgetHours: 80, priority: '1-fire', status: 'query', active: true,
    openedDate: '2025-10-14', dueDate: '2026-01-12', aircraftInputDate: '2025-11-08', closedDate: '',
    scope: ['design', 'certification'], contractCurrency: 'CDN', contractValue: '48000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Awaiting scope confirmation from the customer before quoting.',
    comments: 'Request for quote received; scope still being defined with the customer.',
    aircraft: [{ id: 'ac-rv-764', modelName: 'Dash 8-400', modelNumber: 'DHC-8-402', manufacturer: 'De Havilland' }],
  },
  {
    id: 'rv-772', number: '3189', subNumber: '01', type: 'external',
    title: 'CRJ200 Windscreen/Bulkhead Modification',
    companyName: 'Voyageur Aviation', companyNumber: '193', contactName: 'Nathalie Gagnon', contactEmail: 'nathalie.gagnon@voyageuraviation.example', personResponsible: 'Lloyd Pedvis',
    actualHours: 0.0, budgetHours: 30, priority: '3-med', status: 'query', active: true,
    openedDate: '2025-11-03', dueDate: '2026-03-18', aircraftInputDate: '2025-12-08', closedDate: '',
    scope: ['design', 'validation', 'certification'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Estimate in preparation, engineering review booked this week.',
    comments: 'Budget shown is the working estimate pending a firm scope.',
    aircraft: [{ id: 'ac-rv-772', modelName: 'CRJ200', modelNumber: 'CL-600-2B19', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-743', number: '3272', subNumber: '00', type: 'external',
    title: 'Voyageur - Dash 8-400 Training Aircraft',
    companyName: 'Voyageur Aviation', companyNumber: '193', contactName: 'Nathalie Gagnon', contactEmail: 'nathalie.gagnon@voyageuraviation.example', personResponsible: 'Remi Rocheleau',
    actualHours: 0.0, budgetHours: 18, priority: '4-low', status: 'query', active: true,
    openedDate: '2025-06-18', dueDate: '2025-12-15', aircraftInputDate: '2025-08-02', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '96000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Chasing the customer for aircraft configuration details.',
    comments: 'Request for quote received; scope still being defined with the customer.',
    aircraft: [{ id: 'ac-rv-743', modelName: 'Global Express', modelNumber: 'BD-700-1A10', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-765', number: '3280', subNumber: '00', type: 'external',
    title: 'Cessna Latitude Data Acquisition',
    companyName: 'CAE', companyNumber: '204', contactName: 'Annick Bergeron', contactEmail: 'annick.bergeron@cae.example', personResponsible: 'Kelly Osei',
    actualHours: 0.0, budgetHours: 30, priority: '3-med', status: 'query', active: true,
    openedDate: '2025-09-30', dueDate: '2026-05-13', aircraftInputDate: '2025-11-24', closedDate: '',
    scope: ['design', 'validation'], contractCurrency: 'CDN', contractValue: '310000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Awaiting scope confirmation from the customer before quoting.',
    comments: 'Budget shown is the working estimate pending a firm scope.',
    aircraft: [{ id: 'ac-rv-765', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'rv-773', number: '3283', subNumber: '00', type: 'other',
    title: '*placeholder*',
    companyName: '*', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 18, priority: '4-low', status: 'query', active: true,
    openedDate: '2025-09-26', dueDate: '2026-06-23', aircraftInputDate: '2025-11-30', closedDate: '',
    scope: ['certification', 'aircraft-mod'], contractCurrency: 'CDN', contractValue: '72500',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Estimate in preparation, engineering review booked this week.',
    comments: 'Request for quote received; scope still being defined with the customer.',
    aircraft: [{ id: 'ac-rv-773', modelName: 'Challenger 650', modelNumber: 'CL-600-2B16', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-776', number: '3290', subNumber: '00', type: 'internal',
    title: 'Test Project',
    companyName: 'Elisen', companyNumber: '001', contactName: '—', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 0.0, budgetHours: 30, priority: '3-med', status: 'query', active: true,
    openedDate: '2025-12-11', dueDate: '2026-10-22', aircraftInputDate: '2026-01-05', closedDate: '',
    scope: ['design', 'parts-kit', 'aircraft-mod'], contractCurrency: 'CDN', contractValue: '185000',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Chasing the customer for aircraft configuration details.',
    comments: 'Budget shown is the working estimate pending a firm scope.',
    aircraft: [{ id: 'ac-rv-776', modelName: 'Twin Otter 300', modelNumber: 'DHC-6-300', manufacturer: 'De Havilland' }],
  },
  {
    id: 'rv-721', number: '3257', subNumber: '00', type: 'preferred-duncan',
    title: 'Deviations to approved data on Lear 45',
    companyName: 'Duncan Aviation', companyNumber: '118', contactName: 'Priya Raman', contactEmail: 'priya.raman@duncanaviation.example', personResponsible: 'Lloyd Pedvis',
    actualHours: 0.0, budgetHours: 30, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2024-12-04', dueDate: '2025-03-04', aircraftInputDate: '2025-01-08', closedDate: '',
    scope: ['validation', 'certification'], contractCurrency: 'CDN', contractValue: '54000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2024-12-16', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Quote issued, following up with the customer for a decision.',
    comments: 'Proposal submitted; awaiting customer acceptance.',
    aircraft: [{ id: 'ac-rv-721', modelName: 'A330-300', modelNumber: 'A330', manufacturer: 'Airbus' }],
  },
  {
    id: 'rv-731', number: '3263', subNumber: '00', type: 'external',
    title: 'CL-650 Medevac conversion',
    companyName: 'SAG (Service Aerien Gouvernemental)', companyNumber: '276', contactName: 'Luc Bernier', contactEmail: 'luc.bernier@sagserviceaeriengo.example', personResponsible: 'Remi Rocheleau',
    actualHours: 0.0, budgetHours: 80, priority: '1-fire', status: 'quoted', active: true,
    openedDate: '2025-02-28', dueDate: '2025-07-13', aircraftInputDate: '2025-04-14', closedDate: '',
    scope: ['design', 'certification', 'parts-kit'], contractCurrency: 'CDN', contractValue: '240000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-03-12', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Awaiting purchase order before work can be scheduled.',
    comments: 'Quote covers design substantiation and certification support.',
    aircraft: [{ id: 'ac-rv-731', modelName: 'B737-700', modelNumber: '737-7', manufacturer: 'Boeing' }],
  },
  {
    id: 'rv-738', number: '3268', subNumber: '00', type: 'external',
    title: 'CE Certification - Rudder Lifting Sling',
    companyName: 'Bombardier GX7000/8000', companyNumber: '132', contactName: 'Martin Girard', contactEmail: 'martin.girard@bombardiergx.example', personResponsible: 'Kelly Osei',
    actualHours: 0.0, budgetHours: 30, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2025-04-28', dueDate: '2025-10-25', aircraftInputDate: '2025-06-22', closedDate: '',
    scope: ['design', 'certification'], contractCurrency: 'CDN', contractValue: '68000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-05-10', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Customer reviewing the proposal; check back at month end.',
    comments: 'Proposal submitted; awaiting customer acceptance.',
    aircraft: [{ id: 'ac-rv-738', modelName: 'Learjet 45', modelNumber: 'LJ45', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-740', number: '3270', subNumber: '00', type: 'preferred-duncan',
    title: 'Replace 8.9" Galley Touch screen with 10.1" screen',
    companyName: 'Duncan Aviation', companyNumber: '118', contactName: 'Priya Raman', contactEmail: 'priya.raman@duncanaviation.example', personResponsible: 'Harris Bell',
    actualHours: 0.0, budgetHours: 18, priority: '4-low', status: 'quoted', active: true,
    openedDate: '2025-05-09', dueDate: '2025-12-20', aircraftInputDate: '2025-07-13', closedDate: '',
    scope: ['design', 'validation', 'certification'], contractCurrency: 'CDN', contractValue: '415000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-05-21', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Quote issued, following up with the customer for a decision.',
    comments: 'Quote covers design substantiation and certification support.',
    aircraft: [{ id: 'ac-rv-740', modelName: 'ATR 72-600', modelNumber: 'ATR72', manufacturer: 'ATR' }],
  },
  {
    id: 'rv-744', number: '3273', subNumber: '00', type: 'preferred-duncan',
    title: 'Duncan - GVI Halon Free Fire Extinguisher Modificaiton',
    companyName: 'Duncan Aviation', companyNumber: '118', contactName: 'Priya Raman', contactEmail: 'priya.raman@duncanaviation.example', personResponsible: 'Sofia Reyes',
    actualHours: 0.0, budgetHours: 18, priority: '4-low', status: 'quoted', active: true,
    openedDate: '2025-07-07', dueDate: '2026-04-03', aircraftInputDate: '2025-08-01', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '92000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-07-19', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Awaiting purchase order before work can be scheduled.',
    comments: 'Proposal submitted; awaiting customer acceptance.',
    aircraft: [{ id: 'ac-rv-744', modelName: 'PC-12 NGX', modelNumber: 'PC-12', manufacturer: 'Pilatus' }],
  },
  {
    id: 'rv-752', number: '3281', subNumber: '00', type: 'external',
    title: 'Wet Lavatory Twin Otter 300G',
    companyName: 'De Havilland', companyNumber: '145', contactName: 'Owen Fitzgerald', contactEmail: 'owen.fitzgerald@dehavilland.example', personResponsible: 'Lloyd Pedvis',
    actualHours: 0.0, budgetHours: 50, priority: '2-high', status: 'quoted', active: true,
    openedDate: '2025-10-03', dueDate: '2026-08-14', aircraftInputDate: '2025-11-07', closedDate: '',
    scope: ['design', 'validation'], contractCurrency: 'CDN', contractValue: '156000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-10-15', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Customer reviewing the proposal; check back at month end.',
    comments: 'Quote covers design substantiation and certification support.',
    aircraft: [{ id: 'ac-rv-752', modelName: 'Citation Latitude', modelNumber: 'C680A', manufacturer: 'Cessna' }],
  },
  {
    id: 'rv-756', number: '3285', subNumber: '00', type: 'external',
    title: 'Global Express - Re-upholstery of passenger seats',
    companyName: 'Jenkins Certification Inc.', companyNumber: '463', contactName: 'Alan Jenkins', contactEmail: 'alan.jenkins@jenkinscertificati.example', personResponsible: 'Remi Rocheleau',
    actualHours: 0.0, budgetHours: 30, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2025-09-29', dueDate: '2025-12-28', aircraftInputDate: '2025-11-13', closedDate: '',
    scope: ['certification', 'aircraft-mod'], contractCurrency: 'CDN', contractValue: '48000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-10-11', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Quote issued, following up with the customer for a decision.',
    comments: 'Proposal submitted; awaiting customer acceptance.',
    aircraft: [{ id: 'ac-rv-756', modelName: 'Dash 8-400', modelNumber: 'DHC-8-402', manufacturer: 'De Havilland' }],
  },
  {
    id: 'rv-757', number: '3286', subNumber: '00', type: 'external',
    title: 'DeHavilland -  Zodiac Seat - Removal of Seat Recline Features',
    companyName: 'De Havilland', companyNumber: '145', contactName: 'Owen Fitzgerald', contactEmail: 'owen.fitzgerald@dehavilland.example', personResponsible: 'Kelly Osei',
    actualHours: 0.0, budgetHours: 30, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2025-10-09', dueDate: '2026-02-21', aircraftInputDate: '2025-12-03', closedDate: '',
    scope: ['design', 'parts-kit', 'aircraft-mod'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-10-21', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Awaiting purchase order before work can be scheduled.',
    comments: 'Quote covers design substantiation and certification support.',
    aircraft: [{ id: 'ac-rv-757', modelName: 'CRJ200', modelNumber: 'CL-600-2B19', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-769', number: '3287', subNumber: '00', type: 'external',
    title: 'Dash 8 FMS Software update',
    companyName: 'SAG (Service Aerien Gouvernemental)', companyNumber: '276', contactName: 'Luc Bernier', contactEmail: 'luc.bernier@sagserviceaeriengo.example', personResponsible: 'Harris Bell',
    actualHours: 0.0, budgetHours: 30, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2025-10-29', dueDate: '2026-04-27', aircraftInputDate: '2026-01-02', closedDate: '',
    scope: ['validation', 'certification'], contractCurrency: 'CDN', contractValue: '96000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-11-10', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Customer reviewing the proposal; check back at month end.',
    comments: 'Proposal submitted; awaiting customer acceptance.',
    aircraft: [{ id: 'ac-rv-769', modelName: 'Global Express', modelNumber: 'BD-700-1A10', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-774', number: '3288', subNumber: '00', type: 'external',
    title: 'RCAF 8 Wing - SATCOM Engineering & Installation',
    companyName: 'Voyageur Aviation', companyNumber: '193', contactName: 'Nathalie Gagnon', contactEmail: 'nathalie.gagnon@voyageuraviation.example', personResponsible: 'Sofia Reyes',
    actualHours: 0.0, budgetHours: 50, priority: '2-high', status: 'quoted', active: true,
    openedDate: '2025-11-12', dueDate: '2026-06-25', aircraftInputDate: '2025-12-07', closedDate: '',
    scope: ['design', 'certification', 'parts-kit'], contractCurrency: 'CDN', contractValue: '310000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-11-24', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Quote issued, following up with the customer for a decision.',
    comments: 'Quote covers design substantiation and certification support.',
    aircraft: [{ id: 'ac-rv-774', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'rv-748', number: '3277', subNumber: '00', type: 'preferred-duncan',
    title: 'F2000EX C-GENW - Moving Map and Monitor',
    companyName: 'Duncan Aviation', companyNumber: '118', contactName: 'Priya Raman', contactEmail: 'priya.raman@duncanaviation.example', personResponsible: 'Lloyd Pedvis',
    actualHours: 4, budgetHours: 20, priority: '3-med', status: 'active', active: true,
    openedDate: '2026-03-01', dueDate: '2026-11-26', aircraftInputDate: '2026-04-05', closedDate: '',
    scope: ['design', 'certification'], contractCurrency: 'CDN', contractValue: '72500',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2026-03-13', proposalAccepted: 'yes', proposalAcceptedDate: '2026-03-27',
    nextAction: '2025-10-28 - Elisen to clarify SOW / scope and draft CP',
    comments: 'Aircraft arriving December 2025, and delivery is scheduled for March 2026\nPOC - Joe Walker\n\n2025-11-12 - Revised SoW rec\'d.\n2025-11-10 - Delivery in March 27th\n2025-10-28 - PO# U88617 Rec\'d',
    aircraft: [{ id: 'ac-rv-748', modelName: 'Challenger 650', modelNumber: 'CL-600-2B16', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-770', number: '3282', subNumber: '00', type: 'preferred-duncan',
    title: 'C-GENL Interior upgrade',
    companyName: 'Duncan Aviation', companyNumber: '118', contactName: 'Priya Raman', contactEmail: 'priya.raman@duncanaviation.example', personResponsible: 'Remi Rocheleau',
    actualHours: 5.5, budgetHours: 25, priority: '3-med', status: 'active', active: true,
    openedDate: '2026-03-18', dueDate: '2027-01-27', aircraftInputDate: '2026-05-02', closedDate: '',
    scope: ['design', 'validation', 'certification'], contractCurrency: 'CDN', contractValue: '185000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2026-03-30', proposalAccepted: 'yes', proposalAcceptedDate: '2026-04-13',
    nextAction: 'Elisen to claify SOW and draft CP',
    comments: 'Galley and Lav flooring and, Mid Cabin Cabinet\nPOC - Joe Walker\nPO# U89921 rec\'d 2025-11-03\nScheduled delivery date: 2026/03/21\n\nAircraft inputting in Dec 2025',
    aircraft: [{ id: 'ac-rv-770', modelName: 'Twin Otter 300', modelNumber: 'DHC-6-300', manufacturer: 'De Havilland' }],
  },
  {
    id: 'rv-755', number: '3284', subNumber: '00', type: 'preferred-duncan',
    title: 'Duncan - CL605 C-GKCP Starlink STC Deviations',
    companyName: 'Duncan Aviation', companyNumber: '118', contactName: 'Priya Raman', contactEmail: 'priya.raman@duncanaviation.example', personResponsible: 'Kelly Osei',
    actualHours: 60, budgetHours: 68, priority: '2-high', status: 'active', active: true,
    openedDate: '2025-06-08', dueDate: '2025-09-06', aircraftInputDate: '2025-08-02', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '54000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-06-20', proposalAccepted: 'yes', proposalAcceptedDate: '2025-07-04',
    nextAction: '2025-11-21 - Cert plan awaiting TR signature; DCR in Review; All docs rec\'d from Duncan (except proof of GTP completion) - Package to be finalized.',
    comments: 'Deviations to the Nextant STC for the installation location of the WAP\nPOC - Aaron Lane\nPO # U76158\n\n2025-11-17- Cert Plan in review; to the requested Friday 21 Nov',
    aircraft: [{ id: 'ac-rv-755', modelName: 'A330-300', modelNumber: 'A330', manufacturer: 'Airbus' }],
  },
  {
    id: 'rv-777', number: '3291', subNumber: '00', type: 'preferred-topaces',
    title: '3291 testing description',
    companyName: 'A.I.M.S.', companyNumber: '308', contactName: 'Karim Haddad', contactEmail: 'karim.haddad@aims.example', personResponsible: 'Harris Bell',
    actualHours: 16, budgetHours: 45, priority: '2-high', status: 'active', active: true,
    openedDate: '2025-06-25', dueDate: '2025-11-07', aircraftInputDate: '2025-08-29', closedDate: '',
    scope: ['design', 'validation'], contractCurrency: 'CDN', contractValue: '240000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-07-07', proposalAccepted: 'yes', proposalAcceptedDate: '2025-07-21',
    nextAction: 'TCCA submission being prepared for review.',
    comments: 'Recurring engineering activity tracked against this cost centre.',
    aircraft: [{ id: 'ac-rv-777', modelName: 'B737-700', modelNumber: '737-7', manufacturer: 'Boeing' }],
  },
  {
    id: 'rv-469', number: '3107', subNumber: '00', type: 'external',
    title: 'TCCA sSTC - Q400 Forward Cabin Reconfiguration',
    companyName: 'Air Niugini', companyNumber: '287', contactName: 'Tahawar Durrani', contactEmail: 'tahawar.durrani@airniugini.example', personResponsible: 'Sofia Reyes',
    actualHours: 304.25, budgetHours: 260, priority: '4-low', status: 'active', active: true,
    openedDate: '2025-07-12', dueDate: '2026-01-08', aircraftInputDate: '2025-08-06', closedDate: '',
    scope: ['certification', 'aircraft-mod'], contractCurrency: 'CDN', contractValue: '68000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-07-24', proposalAccepted: 'yes', proposalAcceptedDate: '2025-08-07',
    nextAction: 'ANG have confirmed they have the paint system reccomMended by Elisen\nBurn EO\'S to be created\nInvoice for PCR',
    comments: 'Revised Cert Plan released\nDrawing package released Feb 3\nEI Released\nMDL released\nICA released\nEIC released\nSA released\nFAI no earlier that March 2024 (waiting parts)\nDrawing/EI for PCR released to ANG',
    aircraft: [{ id: 'ac-rv-469', modelName: 'Learjet 45', modelNumber: 'LJ45', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-479', number: '3116', subNumber: '00', type: 'external',
    title: 'Piper Electric Aircraft',
    companyName: 'CAE', companyNumber: '204', contactName: 'Annick Bergeron', contactEmail: 'annick.bergeron@cae.example', personResponsible: 'Lloyd Pedvis',
    actualHours: 7461.44, budgetHours: 7800, priority: '3-med', status: 'active', active: true,
    openedDate: '2025-07-29', dueDate: '2026-03-11', aircraftInputDate: '2025-09-02', closedDate: '',
    scope: ['design', 'parts-kit', 'aircraft-mod'], contractCurrency: 'CDN', contractValue: '415000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-08-10', proposalAccepted: 'yes', proposalAcceptedDate: '2025-08-24',
    nextAction: '- Cert Plan Rev B released\n- FHA A.P06 WIP\n- Evaluate fatigue life - On hold\n- awaiting additional data from Piper\nInstrumentation (3C) request - PO reqd??',
    comments: '2024-09-24 - Rec\'d G-1 at Issue 01\n2023-12-06 - LOPC CM with CAE\n2023-12-04 - EL CM with CAE\n2023-12-04 - FHA transferred to CAE\nSOW and R&R transferred to CAE\nPDR design go ahead provided by CAE\nPDR concepts complete',
    aircraft: [{ id: 'ac-rv-479', modelName: 'ATR 72-600', modelNumber: 'ATR72', manufacturer: 'ATR' }],
  },
  {
    id: 'rv-645', number: '3116', subNumber: '03', type: 'external',
    title: 'eArcher - DDP activities',
    companyName: 'CAE', companyNumber: '204', contactName: 'Annick Bergeron', contactEmail: 'annick.bergeron@cae.example', personResponsible: 'Remi Rocheleau',
    actualHours: 6695.25, budgetHours: 6300, priority: '2-high', status: 'active', active: true,
    openedDate: '2025-08-15', dueDate: '2026-05-12', aircraftInputDate: '2025-09-29', closedDate: '',
    scope: ['validation', 'certification'], contractCurrency: 'CDN', contractValue: '92000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-08-27', proposalAccepted: 'yes', proposalAcceptedDate: '2025-09-10',
    nextAction: 'Wing Battery installation - In sig cycle (waiting for Wedge drawing from CAE)\nClose out installation - In sig cycle\nEngine Truss/install - in sig cycle\nRelease final drawings to CAE ASAP',
    comments: 'All assigned drawings have been released to CAE with exception of wing batteries, engine truss and Aft BHD Closeout\nDDP deviation/out-of-scope tasks sent to CAE October 24',
    aircraft: [{ id: 'ac-rv-645', modelName: 'PC-12 NGX', modelNumber: 'PC-12', manufacturer: 'Pilatus' }],
  },
  {
    id: 'rv-779', number: '3292', subNumber: '00', type: 'external',
    title: '3292 testing description',
    companyName: 'A.I.M.S.', companyNumber: '308', contactName: 'Karim Haddad', contactEmail: 'karim.haddad@aims.example', personResponsible: 'Kelly Osei',
    actualHours: 14.4, budgetHours: 80, priority: '1-fire', status: 'active', active: true,
    openedDate: '2025-09-01', dueDate: '2026-07-13', aircraftInputDate: '2025-10-26', closedDate: '',
    scope: ['design', 'certification', 'parts-kit'], contractCurrency: 'CDN', contractValue: '156000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-09-13', proposalAccepted: 'yes', proposalAcceptedDate: '2025-09-27',
    nextAction: 'Follow up with the customer on outstanding documentation.',
    comments: 'Recurring engineering activity tracked against this cost centre.',
    aircraft: [{ id: 'ac-rv-779', modelName: 'Citation Latitude', modelNumber: 'C680A', manufacturer: 'Cessna' }],
  },
  {
    id: 'rv-780', number: '3293', subNumber: '00', type: 'external',
    title: 'Test project',
    companyName: 'A.I.M.S.', companyNumber: '308', contactName: 'Karim Haddad', contactEmail: 'karim.haddad@aims.example', personResponsible: 'Harris Bell',
    actualHours: 36.8, budgetHours: 80, priority: '1-fire', status: 'active', active: true,
    openedDate: '2025-09-18', dueDate: '2025-12-17', aircraftInputDate: '2025-11-22', closedDate: '',
    scope: ['design', 'certification'], contractCurrency: 'CDN', contractValue: '48000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-09-30', proposalAccepted: 'yes', proposalAcceptedDate: '2025-10-14',
    nextAction: 'TCCA submission being prepared for review.',
    comments: 'Certification project covering design substantiation, compliance documentation and TCCA approval.',
    aircraft: [{ id: 'ac-rv-780', modelName: 'Dash 8-400', modelNumber: 'DHC-8-402', manufacturer: 'De Havilland' }],
  },
  {
    id: 'rv-781', number: '3294', subNumber: '00', type: 'external',
    title: 'Aqeel Test Project',
    companyName: 'Abu Dhabi Aviation', companyNumber: '401', contactName: 'Yusuf Haddad', contactEmail: 'yusuf.haddad@abudhabiaviation.example', personResponsible: 'Sofia Reyes',
    actualHours: 57.6, budgetHours: 80, priority: '1-fire', status: 'active', active: true,
    openedDate: '2025-10-05', dueDate: '2026-02-17', aircraftInputDate: '2025-10-30', closedDate: '',
    scope: ['design', 'validation', 'certification'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-10-17', proposalAccepted: 'yes', proposalAcceptedDate: '2025-10-31',
    nextAction: 'Compliance documentation in progress, draft due to the DAR.',
    comments: 'Modification design and supporting analysis under way.',
    aircraft: [{ id: 'ac-rv-781', modelName: 'CRJ200', modelNumber: 'CL-600-2B19', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-782', number: '3295', subNumber: '00', type: 'external',
    title: 'Aqeel Test Project faizan',
    companyName: '2571768 Ontario inc.', companyNumber: '512', contactName: 'Daniel Ouellet', contactEmail: 'daniel.ouellet@ontarioinc.example', personResponsible: 'Lloyd Pedvis',
    actualHours: 24.8, budgetHours: 80, priority: '1-fire', status: 'active', active: true,
    openedDate: '2025-10-22', dueDate: '2026-04-20', aircraftInputDate: '2025-11-26', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '96000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-11-03', proposalAccepted: 'yes', proposalAcceptedDate: '2025-11-17',
    nextAction: 'Awaiting drawing sign-off before releasing the data package.',
    comments: 'Engineering support against an approved data package.',
    aircraft: [{ id: 'ac-rv-782', modelName: 'Global Express', modelNumber: 'BD-700-1A10', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-730', number: '3261', subNumber: '00', type: 'external',
    title: 'Fireswift ALS review',
    companyName: 'Voyageur Aviation', companyNumber: '193', contactName: 'Nathalie Gagnon', contactEmail: 'nathalie.gagnon@voyageuraviation.example', personResponsible: 'Remi Rocheleau',
    actualHours: 47.0, budgetHours: 50, priority: '2-high', status: 'active', active: true,
    openedDate: '2025-11-08', dueDate: '2026-06-21', aircraftInputDate: '2025-12-23', closedDate: '',
    scope: ['design', 'validation'], contractCurrency: 'CDN', contractValue: '310000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-11-20', proposalAccepted: 'yes', proposalAcceptedDate: '2025-12-04',
    nextAction: 'Ground testing scheduled; report to follow.',
    comments: 'Recurring engineering activity tracked against this cost centre.',
    aircraft: [{ id: 'ac-rv-730', modelName: 'King Air 350', modelNumber: 'BE350', manufacturer: 'Beechcraft' }],
  },
  {
    id: 'rv-732', number: '3262', subNumber: '00', type: 'external',
    title: 'Fireswift design upgrades',
    companyName: 'Metrea', companyNumber: '349', contactName: 'Claire Beaumont', contactEmail: 'claire.beaumont@metrea.example', personResponsible: 'Kelly Osei',
    actualHours: 29.0, budgetHours: 50, priority: '2-high', status: 'active', active: true,
    openedDate: '2025-11-25', dueDate: '2026-08-22', aircraftInputDate: '2026-01-19', closedDate: '',
    scope: ['certification', 'aircraft-mod'], contractCurrency: 'CDN', contractValue: '72500',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-12-07', proposalAccepted: 'yes', proposalAcceptedDate: '2025-12-21',
    nextAction: 'Follow up with the customer on outstanding documentation.',
    comments: 'Certification project covering design substantiation, compliance documentation and TCCA approval.',
    aircraft: [{ id: 'ac-rv-732', modelName: 'Challenger 650', modelNumber: 'CL-600-2B16', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-766', number: '3262', subNumber: '01', type: 'external',
    title: 'Fireswift Hinge bracket re-design',
    companyName: 'Metrea', companyNumber: '349', contactName: 'Claire Beaumont', contactEmail: 'claire.beaumont@metrea.example', personResponsible: 'Harris Bell',
    actualHours: 57.0, budgetHours: 50, priority: '2-high', status: 'active', active: true,
    openedDate: '2025-12-12', dueDate: '2026-10-23', aircraftInputDate: '2026-02-15', closedDate: '',
    scope: ['design', 'parts-kit', 'aircraft-mod'], contractCurrency: 'CDN', contractValue: '185000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-12-24', proposalAccepted: 'yes', proposalAcceptedDate: '2026-01-07',
    nextAction: 'TCCA submission being prepared for review.',
    comments: 'Modification design and supporting analysis under way.',
    aircraft: [{ id: 'ac-rv-766', modelName: 'Twin Otter 300', modelNumber: 'DHC-6-300', manufacturer: 'De Havilland' }],
  },
  {
    id: 'rv-768', number: '3262', subNumber: '03', type: 'external',
    title: 'Fireswift Tank design improvement study',
    companyName: 'Metrea', companyNumber: '349', contactName: 'Claire Beaumont', contactEmail: 'claire.beaumont@metrea.example', personResponsible: 'Sofia Reyes',
    actualHours: 12.5, budgetHours: 50, priority: '2-high', status: 'active', active: true,
    openedDate: '2025-12-29', dueDate: '2026-03-29', aircraftInputDate: '2026-01-23', closedDate: '',
    scope: ['validation', 'certification'], contractCurrency: 'CDN', contractValue: '54000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2026-01-10', proposalAccepted: 'yes', proposalAcceptedDate: '2026-01-24',
    nextAction: 'Compliance documentation in progress, draft due to the DAR.',
    comments: 'Engineering support against an approved data package.',
    aircraft: [{ id: 'ac-rv-768', modelName: 'A330-300', modelNumber: 'A330', manufacturer: 'Airbus' }],
  },
  {
    id: 'rv-746', number: '3275', subNumber: '00', type: 'external',
    title: 'Galileo One Web HDX/FDX installation A330',
    companyName: 'CCX Technologies', companyNumber: '390', contactName: 'Sean Whitfield', contactEmail: 'sean.whitfield@ccxtechnologies.example', personResponsible: 'Lloyd Pedvis',
    actualHours: 33.5, budgetHours: 50, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-01-15', dueDate: '2026-05-30', aircraftInputDate: '2026-02-19', closedDate: '',
    scope: ['design', 'certification', 'parts-kit'], contractCurrency: 'CDN', contractValue: '240000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2026-01-27', proposalAccepted: 'yes', proposalAcceptedDate: '2026-02-10',
    nextAction: 'Awaiting drawing sign-off before releasing the data package.',
    comments: 'Recurring engineering activity tracked against this cost centre.',
    aircraft: [{ id: 'ac-rv-746', modelName: 'B737-700', modelNumber: '737-7', manufacturer: 'Boeing' }],
  },
  {
    id: 'rv-747', number: '3276', subNumber: '00', type: 'external',
    title: 'BBJ737-700',
    companyName: 'B&D Design Services', companyNumber: '455', contactName: 'Brian Doyle', contactEmail: 'brian.doyle@bddesignservices.example', personResponsible: 'Remi Rocheleau',
    actualHours: 44.0, budgetHours: 50, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-02-01', dueDate: '2026-07-31', aircraftInputDate: '2026-03-18', closedDate: '',
    scope: ['design', 'certification'], contractCurrency: 'CDN', contractValue: '68000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2026-02-13', proposalAccepted: 'yes', proposalAcceptedDate: '2026-02-27',
    nextAction: 'Ground testing scheduled; report to follow.',
    comments: 'Certification project covering design substantiation, compliance documentation and TCCA approval.',
    aircraft: [{ id: 'ac-rv-747', modelName: 'Learjet 45', modelNumber: 'LJ45', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-775', number: '3289', subNumber: '00', type: 'external',
    title: 'ATR 72 Aerial Fire Fighter conversionss',
    companyName: 'Chorus Aviation', companyNumber: '221', contactName: 'Derek Hanley', contactEmail: 'derek.hanley@chorusaviation.example', personResponsible: 'Kelly Osei',
    actualHours: 20.5, budgetHours: 50, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-02-18', dueDate: '2026-10-01', aircraftInputDate: '2026-04-14', closedDate: '',
    scope: ['design', 'validation', 'certification'], contractCurrency: 'CDN', contractValue: '415000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2026-03-02', proposalAccepted: 'yes', proposalAcceptedDate: '2026-03-16',
    nextAction: 'Follow up with the customer on outstanding documentation.',
    comments: 'Modification design and supporting analysis under way.',
    aircraft: [{ id: 'ac-rv-775', modelName: 'ATR 72-600', modelNumber: 'ATR72', manufacturer: 'ATR' }],
  },
  {
    id: 'rv-562', number: '0000', subNumber: '00', type: 'internal',
    title: 'Elisen - General (non-chargeable)',
    companyName: 'Elisen', companyNumber: '001', contactName: '—', contactEmail: '', personResponsible: 'Harris Bell',
    actualHours: 10.6, budgetHours: 10, priority: '5-lowest', status: 'active', active: true,
    openedDate: '2026-03-07', dueDate: '2026-12-02', aircraftInputDate: '2026-05-11', closedDate: '',
    scope: ['design'], contractCurrency: 'CDN', contractValue: '92000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2026-03-19', proposalAccepted: 'yes', proposalAcceptedDate: '2026-04-02',
    nextAction: 'TCCA submission being prepared for review.',
    comments: 'Engineering support against an approved data package.',
    aircraft: [{ id: 'ac-rv-562', modelName: 'PC-12 NGX', modelNumber: 'PC-12', manufacturer: 'Pilatus' }],
  },
  {
    id: 'rv-570', number: '0000', subNumber: '01', type: 'internal',
    title: 'Elisen - HR',
    companyName: 'Elisen', companyNumber: '001', contactName: '—', contactEmail: '', personResponsible: 'Sofia Reyes',
    actualHours: 26.0, budgetHours: 50, priority: '2-high', status: 'active', active: true,
    openedDate: '2026-03-24', dueDate: '2027-02-02', aircraftInputDate: '2026-04-18', closedDate: '',
    scope: ['design', 'validation'], contractCurrency: 'CDN', contractValue: '156000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2026-04-05', proposalAccepted: 'yes', proposalAcceptedDate: '2026-04-19',
    nextAction: 'Mechanical designer and interns required\nTS has scheduled Interviews Nov 17 & 18 for (5) mechanical applicants, (4) interns and (1) permanent designer.\nIntern interviews complete with exception of one designer (to be interviewed tomorrow Nov 25)',
    comments: 'Recurring engineering activity tracked against this cost centre.',
    aircraft: [{ id: 'ac-rv-570', modelName: 'Citation Latitude', modelNumber: 'C680A', manufacturer: 'Cessna' }],
  },
  {
    id: 'rv-561', number: '0000', subNumber: '02', type: 'internal',
    title: 'Elisen - Quality System',
    companyName: 'Elisen', companyNumber: '001', contactName: '—', contactEmail: '', personResponsible: 'Lloyd Pedvis',
    actualHours: 7.9, budgetHours: 10, priority: '5-lowest', status: 'active', active: true,
    openedDate: '2025-06-14', dueDate: '2025-09-12', aircraftInputDate: '2025-07-19', closedDate: '',
    scope: ['certification', 'aircraft-mod'], contractCurrency: 'CDN', contractValue: '48000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-06-26', proposalAccepted: 'yes', proposalAcceptedDate: '2025-07-10',
    nextAction: '○ AS9100D Alignment - Update\n○ AS9100 Table - Action CV, ongoing.',
    comments: '• Need additional processes for PWC/3C Project\n• Redline process released',
    aircraft: [{ id: 'ac-rv-561', modelName: 'Dash 8-400', modelNumber: 'DHC-8-402', manufacturer: 'De Havilland' }],
  },
  {
    id: 'rv-347', number: '0000', subNumber: '03', type: 'internal',
    title: 'Elisen - DAO Activities',
    companyName: 'Elisen', companyNumber: '001', contactName: '—', contactEmail: '', personResponsible: 'Remi Rocheleau',
    actualHours: 3.4, budgetHours: 10, priority: '5-lowest', status: 'active', active: true,
    openedDate: '2025-07-01', dueDate: '2025-11-13', aircraftInputDate: '2025-08-15', closedDate: '',
    scope: ['design', 'parts-kit', 'aircraft-mod'], contractCurrency: 'CDN', contractValue: '125000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-07-13', proposalAccepted: 'yes', proposalAcceptedDate: '2025-07-27',
    nextAction: 'DELEGATION\n• TCCA to authorize SD\n• Taif to complete request for extension\n• SD to pursue delegation with Paul\n• DAPM D to be issued (with GB,MD & SoC process)\neSIGNATURES\n• Review & send excel form (TR)\n• Revise DAPM & signature process (HC)',
    comments: '• Signatory system\n• New Delegates application (Stephane)\n• Meeting with TCCA and SD done\n• MD & GB authorized',
    aircraft: [{ id: 'ac-rv-347', modelName: 'CRJ200', modelNumber: 'CL-600-2B19', manufacturer: 'Bombardier' }],
  },
  {
    id: 'rv-569', number: '0000', subNumber: '04', type: 'internal',
    title: 'Elisen - IT',
    companyName: 'Elisen', companyNumber: '001', contactName: '—', contactEmail: '', personResponsible: 'Kelly Osei',
    actualHours: 6.1, budgetHours: 10, priority: '5-lowest', status: 'active', active: true,
    openedDate: '2025-07-18', dueDate: '2026-01-14', aircraftInputDate: '2025-09-11', closedDate: '',
    scope: ['validation', 'certification'], contractCurrency: 'CDN', contractValue: '96000',
    proposalSubmitted: 'yes', proposalSubmittedDate: '2025-07-30', proposalAccepted: 'yes', proposalAcceptedDate: '2025-08-13',
    nextAction: '○ 2023-07 - Cert (GCP) Database development ongoing (Lloyd & Harris).\nImplementation of PDM (3D Experience). Taif to coordinate with Michael D.\nNeed access to 3D Experience',
    comments: '• 2023-07 - Lloyd tasked to incorporate Cert (GCP) Database to TPMS.',
    aircraft: [{ id: 'ac-rv-569', modelName: 'Global Express', modelNumber: 'BD-700-1A10', manufacturer: 'Bombardier' }],
  },
]
