import type { ProjectListRow } from '@/types/project'

/**
 * The client's real Projects Review data, transcribed from their legacy
 * screens (Priorities / Top Aces / Duncan / External / Internal /
 * Outstanding RFQs / Completed RFQs). Those 7 tabs were one `project`
 * table filtered 7 ways — see docs/DECISIONS.md — so this is one flat
 * list, with `status` and `type` carrying what the tab membership used
 * to encode:
 *   status 'query'   = Outstanding RFQ      status 'quoted' = Completed RFQ
 *   status 'active'  = the four type tabs   type            = which type tab
 * `openedDate` on the RFQ rows is back-calculated from the Aging value
 * shown on the legacy screen, so Aging still reads correctly today.
 */
export const REVIEW_ROWS: ProjectListRow[] = [
  {
    id: 'rv-764', number: '3179', subNumber: '07', type: 'external',
    title: 'Pilatus - Additional provisions and console modifications',
    companyName: 'Cert Center Canada (3C)', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '1-fire', status: 'query', active: true,
    openedDate: '2025-10-14', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-772', number: '3189', subNumber: '01', type: 'external',
    title: 'CRJ200 Windscreen/Bulkhead Modification',
    companyName: 'Voyageur Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '3-med', status: 'query', active: true,
    openedDate: '2025-11-03', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-743', number: '3272', subNumber: '00', type: 'external',
    title: 'Voyageur - Dash 8-400 Training Aircraft',
    companyName: 'Voyageur Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '4-low', status: 'query', active: true,
    openedDate: '2025-06-18', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-765', number: '3280', subNumber: '00', type: 'external',
    title: 'Cessna Latitude Data Acquisition',
    companyName: 'CAE', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '3-med', status: 'query', active: true,
    openedDate: '2025-09-30', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-773', number: '3283', subNumber: '00', type: 'other',
    title: '*placeholder*',
    companyName: '*', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '4-low', status: 'query', active: true,
    openedDate: '2025-09-26', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-776', number: '3290', subNumber: '00', type: 'internal',
    title: 'Test Project',
    companyName: 'Elisen', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '3-med', status: 'query', active: true,
    openedDate: '2025-12-11', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-721', number: '3257', subNumber: '00', type: 'preferred-duncan',
    title: 'Deviations to approved data on Lear 45',
    companyName: 'Duncan Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2024-12-04', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-731', number: '3263', subNumber: '00', type: 'external',
    title: 'CL-650 Medevac conversion',
    companyName: 'SAG (Service Aerien Gouvernemental)', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '1-fire', status: 'quoted', active: true,
    openedDate: '2025-02-28', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-738', number: '3268', subNumber: '00', type: 'external',
    title: 'CE Certification - Rudder Lifting Sling',
    companyName: 'Bombardier GX7000/8000', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2025-04-28', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-740', number: '3270', subNumber: '00', type: 'preferred-duncan',
    title: 'Replace 8.9" Galley Touch screen with 10.1" screen',
    companyName: 'Duncan Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '4-low', status: 'quoted', active: true,
    openedDate: '2025-05-09', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-744', number: '3273', subNumber: '00', type: 'preferred-duncan',
    title: 'Duncan - GVI Halon Free Fire Extinguisher Modificaiton',
    companyName: 'Duncan Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '4-low', status: 'quoted', active: true,
    openedDate: '2025-07-07', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-752', number: '3281', subNumber: '00', type: 'external',
    title: 'Wet Lavatory Twin Otter 300G',
    companyName: 'De Havilland', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '2-high', status: 'quoted', active: true,
    openedDate: '2025-10-03', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-756', number: '3285', subNumber: '00', type: 'external',
    title: 'Global Express - Re-upholstery of passenger seats',
    companyName: 'Jenkins Certification Inc.', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2025-09-29', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-757', number: '3286', subNumber: '00', type: 'external',
    title: 'DeHavilland -  Zodiac Seat - Removal of Seat Recline Features',
    companyName: 'De Havilland', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2025-10-09', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-769', number: '3287', subNumber: '00', type: 'external',
    title: 'Dash 8 FMS Software update',
    companyName: 'SAG (Service Aerien Gouvernemental)', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '3-med', status: 'quoted', active: true,
    openedDate: '2025-10-29', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-774', number: '3288', subNumber: '00', type: 'external',
    title: 'RCAF 8 Wing - SATCOM Engineering & Installation',
    companyName: 'Voyageur Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '2-high', status: 'quoted', active: true,
    openedDate: '2025-11-12', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-748', number: '3277', subNumber: '00', type: 'preferred-duncan',
    title: 'F2000EX C-GENW - Moving Map and Monitor',
    companyName: 'Duncan Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 4, budgetHours: 0, priority: '3-med', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '2025-10-28 - Elisen to clarify SOW / scope and draft CP',
    comments: 'Aircraft arriving December 2025, and delivery is scheduled for March 2026\nPOC - Joe Walker\n\n2025-11-12 - Revised SoW rec\'d.\n2025-11-10 - Delivery in March 27th\n2025-10-28 - PO# U88617 Rec\'d',
    aircraft: [],
  },
  {
    id: 'rv-770', number: '3282', subNumber: '00', type: 'preferred-duncan',
    title: 'C-GENL Interior upgrade',
    companyName: 'Duncan Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 5.5, budgetHours: 0, priority: '3-med', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Elisen to claify SOW and draft CP',
    comments: 'Galley and Lav flooring and, Mid Cabin Cabinet\nPOC - Joe Walker\nPO# U89921 rec\'d 2025-11-03\nScheduled delivery date: 2026/03/21\n\nAircraft inputting in Dec 2025',
    aircraft: [],
  },
  {
    id: 'rv-755', number: '3284', subNumber: '00', type: 'preferred-duncan',
    title: 'Duncan - CL605 C-GKCP Starlink STC Deviations',
    companyName: 'Duncan Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 60, budgetHours: 0, priority: '2-high', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '2025-11-21 - Cert plan awaiting TR signature; DCR in Review; All docs rec\'d from Duncan (except proof of GTP completion) - Package to be finalized.',
    comments: 'Deviations to the Nextant STC for the installation location of the WAP\nPOC - Aaron Lane\nPO # U76158\n\n2025-11-17- Cert Plan in review; to the requested Friday 21 Nov',
    aircraft: [],
  },
  {
    id: 'rv-777', number: '3291', subNumber: '00', type: 'preferred-topaces',
    title: '3291 testing description',
    companyName: 'A.I.M.S.', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 16, budgetHours: 0, priority: '2-high', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-469', number: '3107', subNumber: '00', type: 'external',
    title: 'TCCA sSTC - Q400 Forward Cabin Reconfiguration',
    companyName: 'Air Niugini', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 304.25, budgetHours: 0, priority: '4-low', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'ANG have confirmed they have the paint system reccomMended by Elisen\nBurn EO\'S to be created\nInvoice for PCR',
    comments: 'Revised Cert Plan released\nDrawing package released Feb 3\nEI Released\nMDL released\nICA released\nEIC released\nSA released\nFAI no earlier that March 2024 (waiting parts)\nDrawing/EI for PCR released to ANG',
    aircraft: [],
  },
  {
    id: 'rv-479', number: '3116', subNumber: '00', type: 'external',
    title: 'Piper Electric Aircraft',
    companyName: 'CAE', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 7461.44, budgetHours: 0, priority: '3-med', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '- Cert Plan Rev B released\n- FHA A.P06 WIP\n- Evaluate fatigue life - On hold\n- awaiting additional data from Piper\nInstrumentation (3C) request - PO reqd??',
    comments: '2024-09-24 - Rec\'d G-1 at Issue 01\n2023-12-06 - LOPC CM with CAE\n2023-12-04 - EL CM with CAE\n2023-12-04 - FHA transferred to CAE\nSOW and R&R transferred to CAE\nPDR design go ahead provided by CAE\nPDR concepts complete',
    aircraft: [],
  },
  {
    id: 'rv-645', number: '3116', subNumber: '03', type: 'external',
    title: 'eArcher - DDP activities',
    companyName: 'CAE', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 6695.25, budgetHours: 0, priority: '2-high', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Wing Battery installation - In sig cycle (waiting for Wedge drawing from CAE)\nClose out installation - In sig cycle\nEngine Truss/install - in sig cycle\nRelease final drawings to CAE ASAP',
    comments: 'All assigned drawings have been released to CAE with exception of wing batteries, engine truss and Aft BHD Closeout\nDDP deviation/out-of-scope tasks sent to CAE October 24',
    aircraft: [],
  },
  {
    id: 'rv-779', number: '3292', subNumber: '00', type: 'external',
    title: '3292 testing description',
    companyName: 'A.I.M.S.', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '1-fire', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-780', number: '3293', subNumber: '00', type: 'external',
    title: 'Test project',
    companyName: 'A.I.M.S.', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '1-fire', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-781', number: '3294', subNumber: '00', type: 'external',
    title: 'Aqeel Test Project',
    companyName: 'Abu Dhabi Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '1-fire', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-782', number: '3295', subNumber: '00', type: 'external',
    title: 'Aqeel Test Project faizan',
    companyName: '2571768 Ontario inc.', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '1-fire', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-730', number: '3261', subNumber: '00', type: 'external',
    title: 'Fireswift ALS review',
    companyName: 'Voyageur Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '2-high', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-732', number: '3262', subNumber: '00', type: 'external',
    title: 'Fireswift design upgrades',
    companyName: 'Metrea', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '2-high', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-766', number: '3262', subNumber: '01', type: 'external',
    title: 'Fireswift Hinge bracket re-design',
    companyName: 'Metrea', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '2-high', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-768', number: '3262', subNumber: '03', type: 'external',
    title: 'Fireswift Tank design improvement study',
    companyName: 'Metrea', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '2-high', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-746', number: '3275', subNumber: '00', type: 'external',
    title: 'Galileo One Web HDX/FDX installation A330',
    companyName: 'CCX Technologies', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '2-high', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-747', number: '3276', subNumber: '00', type: 'external',
    title: 'BBJ737-700',
    companyName: 'B&D Design Services', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '2-high', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-775', number: '3289', subNumber: '00', type: 'external',
    title: 'ATR 72 Aerial Fire Fighter conversionss',
    companyName: 'Chorus Aviation', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '2-high', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-562', number: '0000', subNumber: '00', type: 'internal',
    title: 'Elisen - General (non-chargeable)',
    companyName: 'Elisen', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '5-lowest', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-570', number: '0000', subNumber: '01', type: 'internal',
    title: 'Elisen - HR',
    companyName: 'Elisen', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '2-high', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'Mechanical designer and interns required\nTS has scheduled Interviews Nov 17 & 18 for (5) mechanical applicants, (4) interns and (1) permanent designer.\nIntern interviews complete with exception of one designer (to be interviewed tomorrow Nov 25)',
    comments: '',
    aircraft: [],
  },
  {
    id: 'rv-561', number: '0000', subNumber: '02', type: 'internal',
    title: 'Elisen - Quality System',
    companyName: 'Elisen', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '5-lowest', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '○ AS9100D Alignment - Update\n○ AS9100 Table - Action CV, ongoing.',
    comments: '• Need additional processes for PWC/3C Project\n• Redline process released',
    aircraft: [],
  },
  {
    id: 'rv-347', number: '0000', subNumber: '03', type: 'internal',
    title: 'Elisen - DAO Activities',
    companyName: 'Elisen', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '5-lowest', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: 'DELEGATION\n• TCCA to authorize SD\n• Taif to complete request for extension\n• SD to pursue delegation with Paul\n• DAPM D to be issued (with GB,MD & SoC process)\neSIGNATURES\n• Review & send excel form (TR)\n• Revise DAPM & signature process (HC)',
    comments: '• Signatory system\n• New Delegates application (Stephane)\n• Meeting with TCCA and SD done\n• MD & GB authorized',
    aircraft: [],
  },
  {
    id: 'rv-569', number: '0000', subNumber: '04', type: 'internal',
    title: 'Elisen - IT',
    companyName: 'Elisen', companyNumber: '', contactName: '—', contactEmail: '', personResponsible: '',
    actualHours: 0.0, budgetHours: 0, priority: '5-lowest', status: 'active', active: true,
    openedDate: '', dueDate: '', aircraftInputDate: '', closedDate: '',
    scope: [], contractCurrency: 'CDN', contractValue: '',
    proposalSubmitted: 'no', proposalSubmittedDate: '', proposalAccepted: 'no', proposalAcceptedDate: '',
    nextAction: '○ 2023-07 - Cert (GCP) Database development ongoing (Lloyd & Harris).\nImplementation of PDM (3D Experience). Taif to coordinate with Michael D.\nNeed access to 3D Experience',
    comments: '• 2023-07 - Lloyd tasked to incorporate Cert (GCP) Database to TPMS.',
    aircraft: [],
  },
]
